### ISSUE TITLE
--v8-option gives "bad option"

### ISSUE THREAD

**Issue by mathiasrw** [nodejs/node-chakracore#10]
Wanting to see if nodeChakra would play nicely with [AlaSQL](https://github.com/agershun/alasql) I installed  [6.0.0-pre2](https://github.com/Microsoft/node/releases/tag/node-chakracore-6.0.0-pre2)  

`npm install` works fin.

When I do a `npm test` I get the message that --v8-option is a "bad option".

So - I cant get to the interesting part (running the tests) because `node --v8-options` is called.

Any plans to support the `--v8-options` flag (as a shim)?

![skaermbillede 2016-01-21 08 55 49](https://cloud.githubusercontent.com/assets/1063454/12474743/bc7d0466-c01d-11e5-8b9e-dc07c6941339.png)

**Comment by kunalspathak** [comment]
Currently chakrashim supports only few flags displayed by `--v8-options` like `--use-strict` and `--expose-gc`. We could update shim to treat `--v8-options` as a valid parameter and it will display only flags supported by chakrashim. I will investigate into this.
Thanks for reporting.

**Comment by mathiasrw** [comment]
:+1:

**Comment by munyirik** [comment]
+1.
I tried using [DNU](https://github.com/aspnet/Home/wiki/DNX-utility) to publish an asp.net app and ran into this error:

F:\Projects\WebApplication1\src\WebApplication1>dnu publish --runtime dnx-coreclr-win-X86.1.0.0-rc1-update1 --out aspx86
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231

Executing script 'prepublish' in project.json
npm WARN EPACKAGEJSON ASP.NET@0.0.0 No description
npm WARN EPACKAGEJSON ASP.NET@0.0.0 No repository field.
npm WARN EPACKAGEJSON ASP.NET@0.0.0 No license field.
Error: Command failed: C:\Program Files\nodejs (chakracore)\node.exe --v8-options
C:\Program Files\nodejs (chakracore)\node.exe: bad option: --help

   at Anonymous function (C:\Users\munyirik\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:182:7)
   at Anonymous function (C:\Users\munyirik\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:157:9)
   at Anonymous function (C:\Users\munyirik\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:115:9)
   at Anonymous function (C:\Users\munyirik\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:70:7)
   at exithandler (child_process.js:209:5)
   at emitTwo (events.js:101:5)
   at emit (events.js:186:7)
   at maybeClose (internal/child_process.js:827:5)
   at Anonymous function (internal/child_process.js:319:11)
   at emitOne (events.js:91:5)
 The 'prepublish' script failed with status code 1.

**Comment by kunalspathak** [comment]
@munyirik , just curious what is the purpose of command in your script?

``` text
Error: Command failed: C:\Program Files\nodejs (chakracore)\node.exe --v8-options
```

**Comment by munyirik** [comment]
It's happening when "gulp clean" is ran. A new ASP.NET 5 application (from Visual Studio template) specifies a series of commands to run (see below). "gulp clean" is where the failure happens. I don't really know what it does.

"prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]

**Comment by mathiasrw** [comment]
@kunalspathak 

Is this included in the 6.0.0-pre4 release?

**Comment by kunalspathak** [comment]
Nope. But it should be included in next release. I have changes ready and will send out PR in next few days.

Sent from Outlook Mobilehttps://aka.ms/blhgte

On Thu, Feb 18, 2016 at 9:55 PM -0800, "Mathias Rangel Wulff" <notifications@github.com<mailto:notifications@github.com>> wrote:

@kunalspathakhttps://github.com/kunalspathak

Is this included in the 6.0.0-pre4 release?

##

**Comment by mathiasrw** [comment]
:+1:

**Comment by mathiasrw** [comment]
:+1:

**Comment by mathiasrw** [comment]
Any news on when you plan to release `pre5`?

**Comment by jianchun** [comment]
@mathiasrw Likely early this week.

**Comment by jianchun** [comment]
@mathiasrw Released. Please help verify if the issue is fixed. Thanks!

**Comment by mathiasrw** [comment]
I can confirm that with the `pre5` release the issue is not present any more. Thanks for the quick response.

**Comment by jianchun** [comment]
@mathiasrw Great, thanks for following up with this issue!

**Comment by Tonacatecuhtli** [comment]
Hi i just updated to node v8.0.0 and now im getting this issue again:
```bash
C:\Users\wisgi> node -v
v8.0.0

C:\Users\wisgi> node --expose_debug_as=v8debug
Program Files\nodejs\node.exe: bad option: --expose_debug_as=v8debug
```

with v7.10.0 this isn't a problem.

OS: Windows10

**Comment by kunalspathak** [comment]
@Tonacatecuhtli - thanks for trying `node-chakracore`. Currently `node-chakracore` only support parameters that you see below.
```cmd
> node --v8-options
Options:
 --use_strict (enforce strict mode)
     type: bool  default: false
 --expose_gc (expose gc extension)
     type: bool  default: false
 --off_idlegc (turn off idle GC)
 --harmony_simd (enable "harmony simd" (in progress))
 --harmony (Other flags are ignored in node running with chakracore)
 --debug (Ignored in node running with chakracore)
 --stack-size (Ignored in node running with chakracore)
```

**Comment by kfarnung** [comment]
@Tonacatecuhtli It looks like you may not be using node-chakracore in this case.  I took a look and node-chakracore's behavior matches the upstream behavior for node.  You would need to report your issue upstream at https://github.com/nodejs/node/issues.

**Comment by Tonacatecuhtli** [comment]
@kfarnung Thanks ok i will do that :)

**Comment by kfarnung** [comment]
@Tonacatecuhtli It looks like V8 removed support for that argument at some point in 5.8.  You can see the removal here:

https://github.com/nodejs/node/commit/60d1aac8d225e844e68ae48e8f3d58802e635fbe#diff-5fb85405f1ec035ec82ebead4371e7e8L4199
