### ISSUE TITLE
Build Instructions for Linux / OS X?

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/node-chakracore#105]
Now that linux is somewhat supported, could the readme be updated with Linux (Unix) build instructions? :D

**Comment by targos** [comment]
They are on the [xplat branch](https://github.com/nodejs/node-chakracore/tree/xplat#linux).

**Comment by jianchun** [comment]
We could consider update main README and use xplat branch source for Linux. The code needs to stay in xplat branch for a while due to experimental APIs.

**Comment by coolaj86** [comment]
+1 macOS (although I'm still on OS X), would love to play with this

**Comment by jianchun** [comment]
@obastemur had tried on OS X and found some additional work needed due to std lib dependencies.

**Comment by obastemur** [comment]
IIRC we had some std lib usage on one of the headers (chakrashim); If we can smooth that part; I will try to handle the rest.

**Comment by leebenson** [comment]
Interim for OS X:

`docker run -ti choas/chakracore node`

> process.versions
> { http_parser: '2.7.0',
>   node: '7.0.0-pre8',
>   chakracore: '1.2.0.0',
>   uv: '1.9.1',
>   zlib: '1.2.8',
>   ares: '1.10.1-DEV',
>   modules: '48',
>   openssl: '1.0.2h' }

**Comment by obastemur** [comment]
#117 should take care of the osx part.

**Comment by Fishrock123** [comment]
@obastemur Are there any OS X prerequisites that need to be added to the build instructions at https://github.com/nodejs/node-chakracore/tree/xplat#linux?

getting this atm:

```
/bin/sh: msbuild: command not found
make[1]: *** [fa6a02b92818e8288f1596ea34d346c4d340f41e.intermediate] Error 127
```

**Comment by obastemur** [comment]
@Fishrock123 assuming you are on `xplat` branch ?
- if you are testing it on a mac with XCode 8.0 installed, that would probably fail to compile. ~~@kunalspathak @jianchun We need to update to latest ChakraCore for Clang compat.~~

Edit: Looks like you already did?? I was able to compile on latest OSX using the steps below

**Comment by obastemur** [comment]
My steps to compile were;

```
git checkout xplat
./configure --engine=chakracore
make
```

**Comment by Fishrock123** [comment]
@obastemur oh, I forgot to checkout the branch. Getting some errors now, see https://github.com/nodejs/node-chakracore/issues/121

**Comment by ghost** [comment]
Hi all, I opened a PR with some instructions for building on Mac Os : https://github.com/nodejs/node-chakracore/pull/164

**Comment by kfarnung** [comment]
This should be resolved, @Fishrock123 please let us know if anything is unclear.
