### ISSUE TITLE
windows specific other platforms are not first class. windows centric is not open

### ISSUE THREAD

**Issue by trendzetter** [nodejs/node-chakracore#11]

**Comment by kunalspathak** [comment]
@trendzetter  - Sorry I didn't understand what is the issue? Could you please elaborate?

**Comment by EdMaurer** [comment]
We welcome your help to bring this to Linux! This version of Node.js is dependent upon ChakraCore's support for other platforms. Linux is the first platform beyond Windows that ChakraCore is targeting as seen in the [roadmap.](https://github.com/Microsoft/ChakraCore/wiki/Roadmap)

**Comment by trendzetter** [comment]
you should not pollute node with you windows centric overhead

@EdMaurer I don't feel like working for free, cleaning up microsofts mess.

**Comment by trendzetter** [comment]
Please delete this issue. I don't want anything to do with chakra or other microsoft parasite implants.
