### ISSUE TITLE
Is NPM slower in Node Chakracore for Ubuntu?

### ISSUE THREAD

**Issue by leebenson** [nodejs/node-chakracore#110]
I'm trying to figure out the source of an npm install bottleneck inside Docker.

Comparing Node proper with Node Chakracore:

**Env 1 - Node 6.5 proper:**

`time docker run node:6.5.0 npm i -g sequelize-cli`

> 0.13s user 0.20s system 1% cpu 22.234 total

**Env 2 - Ubuntu 16.04 LTS x64, Node ChakraCore 7.0.0-pre8**

From this Dockerfile:

``` Dockerfile
FROM ubuntu:16.04

# Install.
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y wget build-essential cmake clang libunwind-dev libicu-dev && \
  wget https://github.com/nodejs/node-chakracore/releases/download/node-chakracore-xplat-7.0.0-pre8/node-chakracore_7.0.0-pre8-Ubuntu16.04_amd64.deb && \
  dpkg -i node-chakracore_7.0.0-pre8-Ubuntu16.04_amd64.deb && \
  rm node-chakracore_7.0.0-pre8-Ubuntu16.04_amd64.deb && \
  rm -rf /var/lib/apt/lists/*
```

Running...

`time docker run chakracore:test npm i -g sequelize-cli`

> 0.01s user 0.01s system 0% cpu 20:27.61 total

**22 seconds vs 20+ minutes**

Any ideas?

**Comment by jianchun** [comment]
Will need to investigate. Meanwhile, at the moment node-chakracore only runs chakra interpreter on Unix. We are working on JIT and other optimizations. Maybe the given install script runs into one such bottleneck?

**Comment by leebenson** [comment]
I get the feeling it's not specific to the install script. I've tried installing several npm packages, and they all seem to be approx. 50-70x slower than npm v3 in a 'native' Node environment. Installing a local `package.json` took over an hour.

**Comment by kunalspathak** [comment]
@leebenson , could you try again with latest [nightly](https://nodejs.org/download/chakracore-nightly/) binaries?

**Comment by leebenson** [comment]
> real	0m20.711s
user	0m18.800s
sys	0m5.000s

MUCH faster. On par with Node proper.
