### ISSUE TITLE
pre9 "Skipping the stack scan"

### ISSUE THREAD

**Issue by alexlamsl** [nodejs/node-chakracore#115]
Just installed `node-chakracore-7.0.0-pre9` (x64) on Windows Server 2012 R2 and run `npm install` on a project and got these:

```



    [0394] Skipping the stack scan



    [0394] Skipping the stack scan



    [047C] Skipping the stack scan



    [047C] Skipping the stack scan
```

**Comment by kunalspathak** [comment]
Thanks for reporting @alexlamsl. I will look into it.

Get Outlook for Androidhttps://aka.ms/ghei36

**Comment by alexlamsl** [comment]
Thanks for looking into this.

FYI, I think there may be two separate issues. Sometimes I only get extraneous blank lines but not those "Skipping the stack scan" messages.

**Comment by kunalspathak** [comment]
I see. Those are the debug message that should not show up in release build.

Get Outlook for Androidhttps://aka.ms/ghei36

**Comment by digitalinfinity** [comment]
@kunalspathak is this issue fixed now? If so, we can close.

**Comment by kunalspathak** [comment]
@alexlamsl , I have updated the binaries under release with the fix. You can install the new version of binary that contains this fix.

**Comment by alexlamsl** [comment]
@kunalspathak thank you very much. I shall give them a try as soon as I get back this evening.

**Comment by alexlamsl** [comment]
@kunalspathak verified - no more extraneous stuff in the console. Thanks for the speedy fix!
