### ISSUE TITLE
installer doesn't add node to path

### ISSUE THREAD

**Issue by doug-wade** [nodejs/node-chakracore#12]
This looks really cool!  I'm trying to get [koa 2.0.0](https://github.com/koajs/koa/issues/533) up and running, since it requires async/await, and I've [heard tell](https://bugs.chromium.org/p/v8/issues/detail?id=4483) this fork supports it.  I'm trying to install using the [msi download](https://github.com/Microsoft/node/releases/download/node-chakracore-6.0.0-pre2/node-chakracore-x64.msi) for pre-release 2.  I'm running on ubuntu 15.04

```
» lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:    15.04
Codename:   vivid
```

When I invoke the installer, I get a wizard that walks me through installation.  It seems to succeed, as does the repair flow.  I checked all the boxes, including the ones that say "Add to PATH".  However, when I check my node version, I still get 5.4.1.

```
» node -v
v5.4.1
```

As I gather, I should be getting v6.0.0.  I'll admit my path isn't the tidiest

```
» echo $PATH
/home/doug/.rvm/gems/ruby-1.9.3-p547/bin:/home/doug/.rvm/gems/ruby-1.9.3-p547@global/bin:/home/doug/.rvm/rubies/ruby-1.9.3-p547/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/doug/.rvm/bin:/bin:/home/doug/bin
```

but there doesn't seem to be anything obviously wrong with it, though my node is pretty early on it

```
» which node
/usr/local/bin/node  
```

I tried building from source, but the link to download visual studio, https://www.visualstudio.com/en-us/downloads/download-visual-studio%0A-vs.aspx, is broken -- I get

```
Bad Request - Invalid URL

HTTP Error 400. The request URL is invalid.
```

so I can't build from source.  Have a made a mistake of some kind?  I use [n as my node version manager](https://github.com/tj/n).

**Comment by jianchun** [comment]
@doug-wade I'm very confused. This build of Node.js with chakracore only runs on Windows. We are working hard to make it cross-platform. How could you install it on Ubuntu?

Thanks for reporting the broken link... not sure how that happened. Will follow up.

**Comment by kunalspathak** [comment]
@doug-wade , I have fixed the broken link for VS installer.

**Comment by doug-wade** [comment]
@jianchun oh, I didn't realize -- that's very disappointing.  nevermind, then.

@kunalspathak thanks!

**Comment by jianchun** [comment]
> @jianchun oh, I didn't realize -- that's very disappointing.  nevermind, then.

@doug-wade  We are working on it. You can track our progress here (still very early): https://github.com/Microsoft/ChakraCore/tree/linux
