### ISSUE TITLE
Undefined symbol loading an addon under Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by ChrisMunt** [nodejs/node-chakracore#120]
Version: v7.0.0-pre
Platform: Linux ubuntu 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Subsystem: My C++ addon,

I have been testing the build procedure for porting C++ based addons from Node.js/V8 to Node.js/chakracore and have started with a very simple class for testing.  The C++ code is shown below.  Basically, it contains one method that accepts one input ("Hello" in my example) and concatenates "World" to form the output.  This addon builds and works fine under Windows 10.  It builds successfully under Linux but there is an undefined symbol reported when Node.js attempts to load it.
# C++ Code (cmtest1.cpp)

```
// Simple test for Node.js (cmtest1.cpp)
# include <v8.h>
# include <node.h>
# include <node_object_wrap.h>
# include <string.h>

using namespace node;
using namespace v8;

class cmtest1 : public node::ObjectWrap
{
private:

   int m_count;

public:

   static Persistent<Function> s_ct;

   static void Init(Handle<Object> target)
   {
      Isolate\* isolate = Isolate::GetCurrent();

  Local<FunctionTemplate> t = FunctionTemplate::New(isolate, New);
  t->InstanceTemplate()->SetInternalFieldCount(1);
  t->SetClassName(String::NewFromUtf8(isolate, "cmtest1"));

  NODE_SET_PROTOTYPE_METHOD(t, "method", Method);

  s_ct.Reset(isolate, t->GetFunction());

  target->Set(String::NewFromUtf8(isolate, "cmtest1"), t->GetFunction());

   }

   cmtest1() :
      m_count(0)
   {
   }

   ~cmtest1()
   {
   }

   static void New(const FunctionCallbackInfo<Value>& args)
   {
      Isolate\* isolate = args.GetIsolate(); \
      HandleScope scope(isolate); \
      cmtest1 *c = new cmtest1();
      c->Wrap(args.This());


  args.GetReturnValue().Set(args.This());
  return;


   }

   static void Method(const FunctionCallbackInfo<Value>& args)
   {
      char c_input[256], c_output[256];
      Isolate\* isolate = args.GetIsolate();
      HandleScope scope(isolate);


  Local<String> input = args[0]->ToString();
  input->WriteUtf8(c_input);

  strcpy(c_output, c_input);
  strcat(c_output, " World");

  Local<String> output = String::NewFromUtf8(isolate, c_output);

  args.GetReturnValue().Set(output);
  return;


   }

};

Persistent<Function> cmtest1::s_ct;

extern "C" {
# if defined(_WIN32)

   void __declspec(dllexport) init (Handle<Object> target)
# else

   static void init (Handle<Object> target)
# endif

   {
       cmtest1::Init(target);
   }

   NODE_MODULE(cmtest1, init);
}
```
# JavaScript Code for testing the module shown above (cmtest1.js)

var globals = require('cmtest1');
var user = new globals.cmtest1();
console.log("\n\n" + user.method("Hello"));

I successfully built Node.js/chakracore from source and it is installed under /opt/nodeck/
# The build process

root@ubuntu:/opt/cm/node# node-gyp configure --nodedir=/opt/nodeck
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@7.0.0-pre | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/opt/nodeck/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/cm/node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/nodeck/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/nodeck/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/opt/nodeck',
gyp info spawn args   '-Dnode_gyp_dir=/opt/nodeck/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/cm/node',
gyp info spawn args   '-Dnode_engine=chakracore',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok

root@ubuntu:/opt/cm/node# node-gyp build --nodedir=/opt/nodeck
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@7.0.0-pre | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/opt/cm/node/build'
  CXX(target) Release/obj.target/cmtest1/cmtest1.o
  SOLINK_MODULE(target) Release/obj.target/cmtest1.node
  COPY Release/cmtest1.node
make: Leaving directory '/opt/cm/node/build'
gyp info ok

All looks good and cmtest1.node is created.  However ...
# Running the JS test (cmtest1.js)

root@ubuntu:/opt/cm/node/build/Release# node cmtest1.js
node: symbol lookup error: /opt/cm/node/build/Release/cmtest1.node: undefined symbol: _ZN2v89Signature3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEE
root@ubuntu:/opt/cm/node/build/Release#

Many thanks for reading this.

Chris.

**Comment by kunalspathak** [comment]
@obastemur , do you want to take a look?

**Comment by obastemur** [comment]
@ChrisMunt Thanks for the details.

```
root@ubuntu:/opt/cm/node/build/Release# node cmtest1.js
```

Do you have node-chakracore is installed to path ? Because when you call `node cmtest1.js` that calls the `node` from path. Could you please try `./node` ?

**Comment by ChrisMunt** [comment]
Many thanks for the response.  As a Node.js addon developer I have quite a few Node (V8) installations on my system but none in the path.  Here's a complete audit of what I have done so far.

First, creating the node-chakracore build.  I followed the instructions in ...

https://github.com/nodejs/node-chakracore/tree/xplat#linux

I made sure I had up-to-date versions of the packages required for building.

Commands used ...

git clone https://github.com/nodejs/node-chakracore.git
cd node-chakracore
git checkout xplat
./configure --engine=chakracore --prefix=/opt/nodeck
make
make install

This gave me a working installation in /opt/nodeck ...

root@ubuntu:/opt/cm/node# /opt/nodeck/bin/node -v
v7.0.0-pre

Now, working in /opt/cm/node ...

root@ubuntu:/opt/cm/node#

In this directory, I have the source shown previously (cmtest1.cpp) and the 'binding.gyp' file ...

root@ubuntu:/opt/cm/node# cat binding.gyp
{
  "targets": [
    {
      "target_name": "cmtest1",
      "sources": [ "cmtest1.cpp" ]
    }
  ]
}

I don't have any Node installation in the path ...

root@ubuntu:/opt/cm/node# node
The program 'node' is currently not installed. You can install it by typing:
apt install nodejs-legacy
root@ubuntu:/opt/cm/node# node-gyp
The program 'node-gyp' is currently not installed. You can install it by typing:
apt install node-gyp
root@ubuntu:/opt/cm/node#

Setting the path as node-gyp won't operate without 'node' in the path ...

root@ubuntu:/opt/cm/node# export PATH=$PATH:/opt/nodeck/bin:/opt/nodeck/lib/node_modules/npm/bin/node-gyp-bin
root@ubuntu:/opt/cm/node#

Now ...

root@ubuntu:/opt/cm/node# node -v
v7.0.0-pre
root@ubuntu:/opt/cm/node# node-gyp -v
v3.3.1
root@ubuntu:/opt/cm/node#

Build cmtest1.node ...

root@ubuntu:/opt/cm/node# node-gyp configure --nodedir=/opt/nodeck
root@ubuntu:/opt/cm/node# node-gyp build --nodedir=/opt/nodeck

Build successful ...

root@ubuntu:/opt/cm/node# ls -l ./build/Release/*.node
-rwxr-xr-x 1 root root 20224 Sep 23 01:34 ./build/Release/cmtest1.node
root@ubuntu:/opt/cm/node#

Now try to load this module using full paths throughout ...

root@ubuntu:/opt/cm/node# /opt/nodeck/bin/node -v
v7.0.0-pre
root@ubuntu:/opt/cm/node# /opt/nodeck/bin/node

> var test = require('/opt/cm/node/build/Release/cmtest1.node')
> /opt/nodeck/bin/node: symbol lookup error: /opt/cm/node/build/Release/cmtest1.node: undefined symbol: _ZN2v89Signature3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEE
> root@ubuntu:/opt/cm/node#

Thanks again for looking at this.  It would be interesting to know whether or not you can reproduce this issue locally.

Chris.

**Comment by jianchun** [comment]
@ChrisMunt Thanks for reporting and posting the details. I tried it and (weirdly) it worked for me. Admittedly we haven't looked at building native addons on Linux with node-chakracore at all.

```
xjc@ubun:~/tmp$ node cmtest1.js 


Hello World
```

I examined the symbol and my version looks a little bit different to yours:

```
xjc@ubun:~/tmp$ nm build/Release/cmtest1.node | grep _ZN2v89Signature3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEE
                 U _ZN2v89Signature3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEEiPS5_
```

Note mine has extra `iPS5_` at the end...

And the symbol exists in node binary:

```
xjc@ubun:~/tmp$ objdump -T /usr/local/bin/node | grep _ZN2v89Signature3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEE
0000000000ad20d0 g    DF .text  0000000000000024  Base        _ZN2v89Signature3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEEiPS5_
```

**Comment by obastemur** [comment]
IMO we have an issue here that we may need to address.

@ChrisMunt One possible bottle-neck. Since the missing signature belongs to a `FunctionTemplate`, I was wondering whether we actually publish our header files on `make install`

Actually we don't. `output_folder/include/node` path has the `v8.h` from deps/v8

@jianchun @kunalspathak any opinions on putting our header files into install output folder? (we may need to update couple of common python etc. files)

**Comment by jianchun** [comment]
@obastemur That is a good point. @ChrisMunt was using `--nodedir=/opt/nodeck`. I was using `--nodedir=[my node-chakracore clone dir]`.

Yes there are likely problems here, as I mentioned we hadn't got chance to look at native addons. I can't check right now; but the node-gyp and top-level config.gypi should both be customized and they should be pointing to deps/chakrashim's headers. If the headers are missing we should get a compile time error.

**Comment by ChrisMunt** [comment]
Many thanks for the feedback.  I was able to get the addon to build using '--nodedir=[my node-chakracore clone dir]'.  And I was able to build a far more substantial addon implementing an interface to a database.  I appreciate that it's early days with the node-chakracore initiative but it seems to be looking good so far...

**Comment by obastemur** [comment]
@ChrisMunt Can we assume, this no longer an issue for you (using the tip above) ?

**Comment by ChrisMunt** [comment]
Yes, this is resolved now.  Many thanks for the help.
