### ISSUE TITLE
"Cannot Execute" error when using the prebuild node executable on WinCE with ARM processor

### ISSUE THREAD

**Issue by avadhutbhangui** [nodejs/node-chakracore#127]
- **Version**: Node v7.0.0-pre9
- **Platform**: WinCE on ARM
- **Subsystem**: 

I downloaded the prebuilt node executable with chackracore.dll file and put it on my system which runs WinCe on a ARM processor. Whenever i run it i get an error "Cannot execute <path to node.exe>" error on the command prompt.

Can you please help me to understand why this error and how it can be overcome?

Thanks
/Avadhut.

**Comment by digitalinfinity** [comment]
@avadhutbhangui currently node-chakracore is supported only on Win7 SP1 and above. Can you give us some more insight into your scenario please?

**Comment by avadhutbhangui** [comment]
Hello,

I have a system which runs on WinCE on ARM processor. I'm trying to see a possibility of running node.js inside this system (i.e. basically on WinCE). So i was trying to see if we have a node.js build which is compatible with ARM processor. Eventually i learnt that it's for ARM processor, but the target operating system is Windows 10.x and not WinCE. So this option is ruled out now.

Now, i'm just trying to see if there is a possibility of building the node-chakracore source for WinCE. I'm not  sure, if this will be a right thing to do. Can you please provide your inputs?

/Avadhut.

**Comment by aruneshchandra** [comment]
@avadhutbhangui node-ChakraCore relies on [ChakraCore](https://github.com/microsoft/chakraCore/) support for the underlying platform. And since WinCE is not a supported platform building the sources for Node-ChakraCore itself will not be sufficient. You will have to port ChakraCore to WinCE for your scenario to work.

**Comment by avadhutbhangui** [comment]
Thanks!
