### ISSUE TITLE
Is there way to detect that the code is running on Node.js Chakra?

### ISSUE THREAD

**Issue by hgwood** [nodejs/node-chakracore#13]
This could be helpful to conditionally activate [UWP](https://github.com/Microsoft/node-uwp)-specific modules.

**Comment by xieranmaya** [comment]
Should be the `process.release`
https://nodejs.org/dist/latest-v5.x/docs/api/process.html#process_process_release

**Comment by kunalspathak** [comment]
We introduced property `jsEngine` on `process` object.

``` js
process.jsEngine == 'chakra'; // for chakra engine
process.jsEngine == 'v8'; // for v8
```

**Comment by hgwood** [comment]
Great, thanks. I will try that.
