### ISSUE TITLE
Buffer's `new`.

### ISSUE THREAD

**Issue by houd1ni** [nodejs/node-chakracore#131]
- **Version**: v7.0.0-pre9
- **Platform**: Win10

Hello! I have this console output when use browserify stack:

> (node:8672) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

However, [Documentation](https://nodejs.org/api/buffer.html#buffer_new_buffer_array) tells that we should drop `new`. How to deal with it? Is it a bug?

**Comment by alexlamsl** [comment]
I believe this deprecation is added in `nodejs` codebase, not specific to `node-chakracore`.

And I think this is reported and tracked in https://github.com/substack/node-browserify/issues/1616

**Comment by houd1ni** [comment]
@alexlamsl  Oh, thank you very much! The problem has spawned just after upgrade, which was also from 6.x version.  I was afraid of `new` proposal, which is deprecated itself. :roll_eyes:
