### ISSUE TITLE
How do I use it ?

### ISSUE THREAD

**Issue by warpdesign** [nodejs/node-chakracore#14]
I installed ChakraCore from here https://github.com/Microsoft/node/releases

The readme states that `This Node.js will work side-by-side with any existing Node.js with v8 installation.`.

But how do I use it ? From a command line, `node --version` still points to my existing nodejs with v8 installation.

**Comment by jianchun** [comment]
@warpdesign Seems your existing nodejs with v8 is in your PATH. To try out Node.js with ChakraCore, you can launch "Node.js (chakracore)" or "Node.js (chakracore) command prompt" from Windows Start.

**Comment by warpdesign** [comment]
Yes, it is indeed. Thanks!

I suggess adding in the readme file that these two new entries are added to the start screen for trying out chakracore Node.js.

**Comment by aruneshchandra** [comment]
Added "You can look for "Node.js (chakracore) command prompt" in your start menu to launch Node.js with ChakraCore." it to this to release descriptions.
