### ISSUE TITLE
TypeError: Object doesn't support property or method 'ToString'

### ISSUE THREAD

**Issue by hemanth** [nodejs/node-chakracore#150]
```sh
$ node -v
v7.0.0-nightly20161130efeaf88f0c
```

```sh
$ uname -a
Darwin LM-BNG-26500020 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
```

<img width="589" alt="screen shot 2016-12-01 at 1 59 20 pm" src="https://cloud.githubusercontent.com/assets/18315/20786899/ea6c64b2-b7ce-11e6-9ba4-47ce84e812ac.png">

**Comment by kunalspathak** [comment]
Thanks @hemanth for reporting. Confirmed that it is reproing on windows as well. We will take a look.

**Comment by alexlamsl** [comment]
Also reproduced on `node-chakracore 7.0.0-pre9` (Windows)

**Comment by kunalspathak** [comment]
Fixed in latest nightly version. Tried on ` node: '8.0.0-nightly20170301fd355edcd9'`.

**Comment by hemanth** [comment]
Curious about the fix.

**Comment by kunalspathak** [comment]
Last time I investigated, the `TypeError` was coming because `formatValue` was trying to perform `toString` on a `Symbol` that was broken in chakrashim. With latest changes in Chakracore and I am assuming some refactoring in `lib\util.js`, this seems to be fixed.

**Comment by hemanth** [comment]
:+1:
