### ISSUE TITLE
Change the default branch x-plat

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/node-chakracore#152]
@thefourtheye - can you please change the default branch on nodejs/node-ChakraCore repo to x-plat ?
And also can you please add @digitalinfinity, @kunalspathak and @aruneshchandra as the owners of the repo?

**Comment by Fishrock123** [comment]
@thefourtheye Did you complete this? Seems like default branch was changed.

@aruneshchandra Don't be afraid to @nodejs/tsc if you need any repo-management help. :)

**Comment by digitalinfinity** [comment]
Yup, @thefourtheye helped with this- closing this issue.
