### ISSUE TITLE
Debugger problem with VS Code (request 'evaluate' was cancelled error)

### ISSUE THREAD

**Issue by munyirik** [nodejs/node-chakracore#153]
* **Version**: 7.0.0-pre10
* **Platform**: Windows 10
* **Subsystem**: Debugger

Repro steps:
1. Start node with --debug flag
2. In VS Code attempt to attach to the node process.

Result:
![capture png](https://cloud.githubusercontent.com/assets/8389594/20908744/cfb38656-bb0b-11e6-9e44-ad5c1df10162.jpg)

**Comment by aruneshchandra** [comment]
@munyirik are you using [VSCode Insiders](https://code.visualstudio.com/insiders) ?

**Comment by munyirik** [comment]
Using version 1.7.2. @agarwal-sandeep mentioned that the issue is that the latest release isn't synced to node-ChakraCore/master.

cc @kunalspathak

**Comment by kunalspathak** [comment]
AFAIK, debugger should just work with build from xplat branch because that is the one we demoed in node interactive. The debugging support for VS code is in nightly builds as @aruneshchandra  pointed.

**Comment by munyirik** [comment]
Ah so I need to use a VSCode Insiders build?

**Comment by aruneshchandra** [comment]
yes!

**Comment by munyirik** [comment]
I just tried the Insider build (1.8.0-insider) and I'm seeing the same problem.

**Comment by munyirik** [comment]
I just tried this with the --debug-brk flag and it works. So the problem looks like it's with the --debug flag.

**Comment by Cellule** [comment]
I get the same problem when putting `"runtimeArgs: [""]` in my launch configuration.
From the console the difference seems to be `--nolazy` is missing when using the above config.

My full config
```json
{
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "nodech",
      "name": "Launch Program",
      "program": "${workspaceRoot}/test.js",
      "runtimeArgs": [
        ""
      ]
    },
```
Where `nodech` is node for chakracore on my path.
Also, I am using latest chakracore.dll

**Comment by kfarnung** [comment]
I'm not seeing this issue with the inspector implementation, please try it out and open a new issue for any problems you see.
