### ISSUE TITLE
TTD -- flag compatibility check -TTBreakFirst flag only used with -TTDebug

### ISSUE THREAD

**Issue by mrkmarron** [nodejs/node-chakracore#159]
* **v7.0.0-pre w/ ChakraCore**:
* **All platforms**:
* **Time-Travel Debugging**:

Using -TTBreakFirst without also specifying -TTDebug will results in crash when accessing debug object (which may not be set). Need to check flag use and provide friendly message.

**Comment by mrkmarron** [comment]
Generalizing this a bit. Currently there are a number of assumptions about which flags are compatible/incompatible and incorrect combinations lead to failures with unhelpful outputs.

- TTRecord with any debug flag (including --debug, --debug-brk, -TTBreakFirst, etc.) all cause unusual failures.
- TTReplay with any debug flag (including --debug, --debug-brk, -TTBreakFirst, etc.) also fail.

All of these should be explicitly checked for and helpful usage messages printed.

**Comment by sidkshatriya** [comment]
What is the difference between "TTReplay" (mentioned in the above comment) and "TTDebug". Are they the same?

**Comment by mrkmarron** [comment]
Replay mode (-TTReplay) re-executes the recorded events/code (without enabling the debugger) and then exits so most users will want to use the -TTDebug for debugging but there are cases where just being able to replay the execution and gather additional information is useful. For example you could replay the code on an instrumented version of node-chakracore that records how many times each loop is executed, which loops are jitted, etc.

**Comment by sidkshatriya** [comment]
I am interested in the ability to do "information collection" (or instrumentation) without doing modifications to Node Chakra Core engine itself. For example write a "driver" program in JavaScript (or some other HLL) that can run the recorded trace on ChakraCore and introspect the trace as it runs and when it enters, say, functions it can collect the value of the arguments and so forth. In some ways this specific example could be done by a profiler but I want to be able to have full flexibility as I traverse the program (possibly back and forth, inside and up call stacks).

Can I do this on ChakraCore/NodeChakraCore?

I suppose I could emulate the node debug protocol and then do some evals() using the debugger interface but is there an easier way?

**Comment by mrkmarron** [comment]
Currently there is no supported set of api hooks for doing dynamic tracing in JavaScript (or in the engine) during replay. I wanted to get a better understanding of use cases around replay tracing before trying to do this. However, it should be possible to build some fairly complex information collection tools with the current system and a little creativity. 

Since the replay system re-loads and re-executes the JavaScript code you can actually make some fairly major changes to the code that runs in replay without causing problems. For example suppose that you want to count how many methods are invoked in the following program:
```
function world() {
  console.log("world");
}

function hello() {
  console.log("hello");
}

function doIt() {
  hello();
  world();
}

setTimeout(doIt, 10);
```
You can manually re-write it or use your favorite JavaScript re-writer (e.g., [esprima](http://esprima.org/)) to insert the instrumentation calls you need but leave them as nops so the performance impact is minimized as follows:
```
var callCount = 0;
function incCallCount() {
  callCount++;
}

var functionEnterCallback = function() {}

function world() {
  functionEnterCallback();
  console.log("world");
}

function hello() {
  functionEnterCallback();
  console.log("hello");
}

function doIt() {
  if(0) { functionEnterCallback = incCallCount; }

  functionEnterCallback();
  hello();
  world();

  telemetryLog(`Call count ${callCount}.`, true);
}

setTimeout(doIt, 10);
```
You can then run this program in record mode as usual and the output will be "Call count 0". Once you have the recording you can find the .js file that is part of the log (in my case it is ttlog\src_29.js) and change the line `if(0) { functionEnterCallback = incCallCount; }` to `if(1) { functionEnterCallback = incCallCount; }`. Now if you replay the program it will report an error on the `telemetryMsg` call but you will see the "New Msg" is now "Call count 3" since the `functionEnterCallback` function is being set to `incCallCount` instead of remaining a nop. 

As you can see there are some limits to this approach. If you want to eliminate the error on telemetryLog you will need to recompile ChakraCore to not assert the message strings are the same (`ReplayTelemetryLogEvent` in `TTEventLog.cpp`). It is also important that the logging code does not perform any actions that create log events (creating dates, random numbers, enumerating an objects properties, and of course doing any I/O). Also the use of 0/1 in the conditional is critical as the change cannot alter the length of the code file. 

This is definitely **not a supported use case**  at this point in time so there will likely be some other technical issues that come up using this approach but they can be addressed as they arise. I also expect trying to do this in the context of the debugger will be problematic so I would stick with just replaying to start out.

**Comment by mrkmarron** [comment]
Added info to --help and checks for appropriate usage in PR #180.
