### ISSUE TITLE
6.0.0-pre3 wrong version string

### ISSUE THREAD

**Issue by alexlamsl** [nodejs/node-chakracore#16]
It's not that important, but I couldn't find anywhere else to comment on this.

The latest MSI release is still reporting as `6.0.0-pre2` when I run `node -v`, which makes me initially thought the upgrade failed.

**Comment by kunalspathak** [comment]
Thanks @alexlamsl  for reporting this. I have fixed the binaries to reflect version `v6.0.0-pre3`.

**Comment by alexlamsl** [comment]
Installed and verified. Thanks!
