### ISSUE TITLE
FATAL ERROR when trying time traveling debugging on vscode

### ISSUE THREAD

**Issue by Josema** [nodejs/node-chakracore#163]
* **Version**: v7.0.0-nightly201612169538b4aa4f
* **Platform**: Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64
* **Subsystem**: OSX El capitan v10.11.2
* **VScode version**: 1.8.1 (1.8.1)

Installed node-chakra via nvs. And followed this tutorial to install it with vscode http://www.mattzeunert.com/2016/12/22/vs-code-time-travel-debugging.html

The script is running correctly, but when I click on **Step Back** this is the output:
```
/Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --debug-brk=36020 test/transports/broadcast.js 
Debugger listening on 127.0.0.1:36020
FATAL ERROR: internal error ../deps/chakrashim/src/jsrtdebug.cc(343): 10001
Important: This didn't happen because of an uncaught Javascript exception.
```

**Comment by agarwal-sandeep** [comment]
@josema Thanks for trying TTD.
Based on above command line it seems you are not replaying a TTD recorded session so there is no Stepping back. For TTD first a session needs to be recorded using steps in "Record replay data" and then can be replayed using -TTRecord.

**Comment by Josema** [comment]
Could you explain what is a recorded session? And how I can initiate it? Is an argument?
Btw this is my setup:
```
        {
            "name": "Chakra",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/${relativeFile}",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "/Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node",
            "runtimeArgs": []
        },
```

**Comment by digitalinfinity** [comment]
Hi @Josema- the instructions for Time Travel Debugging are [Here](https://github.com/nodejs/node-chakracore/blob/xplat/TTD-README.md). Specifically, in your case you need to set your runtime args to something like the following:
`"runtimeArgs": ["-TTDebug:log", "-TTBreakFirst"]`

Replace log with whatever argument you supplied to -TTRecord when you captured the trace.

**Comment by kunalspathak** [comment]
I think we should keep this issue open to not crash with `FATAL ERROR` that @Josema is seeing.

**Comment by Josema** [comment]
@digitalinfinity Doing that i have this error:
```
/Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --debug-brk=13166 -TTDebug:log -TTBreakFirst test/protocol/mutations.js 
Filename: /Users/enzo/Copy/projects/dop/dop/log/ttdlog.log
Error is: 2 No such file or directory
Message is: Failed File Open
TTD assert failed: Trying to read a invalid file.
```

And if I create the file this is the output:
```
/Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --debug-brk=19283 -TTDebug:log -TTBreakFirst test/protocol/mutations.js 
Error is: 87 Shared library version mismatch
Message is: Failed Read!!!
TTD assert failed: Not sure what happened
```

I gave `chmod 777 ttdlog.log` but same error.

**Comment by mrkmarron** [comment]
Hi @Josema, just to make sure we are on the same page here can you run a few things for me (my example is on Windows but the commands/steps are the same). I have a simple node application `app.js` in the folder `HelloWorld` with the contents:
```
function hello() {
  var msg = 'Hello world!';
  telemetryLog(msg, true);
}

setTimeout(hello, 10);
```
From the nightly build directory I can run the following command to get a "recorded session" in the directory "log":
```
c:\Chakra\node-v7.0.0-nightly>node.exe --nolazy -TTRecord:log HelloWorld\app.js
```
You should be able to see the recorded data in the newly created directory `` To verify that everything is worked correctly I can replay this recorded session with the command:
```
c:\Chakra\node-v7.0.0-nightly>node.exe --nolazy -TTReplay:log
```
It should output the following:
```
Hello world!

Reached end of Execution -- Exiting.
```
If you see this then everything is working correctly. To use time-travel in VSCode you should add the following launch configuration (changing the paths as needed for your environment):
```
{
    "name": "TTD",
    "type": "node",
    "request": "launch",
    "program": "${workspaceRoot}/app.js",
    "cwd": "c:\\Chakra\\node-v7.0.0-nightly\\",
    "runtimeExecutable": "c:\\Chakra\\node-v7.0.0-nightly\\node.exe",
    "runtimeArgs": [
        "--nolazy",
        "--debug",
        "-TTDebug:log",
        "-TTBreakFirst" 
    ],
    "env": {
        "NODE_ENV": "development"
    },
    "console": "internalConsole"
}
```
If you set a breakpoint at the `telemetryLog(msg, true);` line and launch this configuration it should break there and you can then step-back. 

If this works then you can repeat the steps with your `test/transports/broadcast.js` application and things should be working for that code as well. Please let us know if this clears things up.

**Comment by Josema** [comment]
Hi @mrkmarron 
Running:
```
$ /Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --nolazy -TTRecord:log app.js
Hello world!
```
Running:
```
$ /Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --nolazy -TTRecord:log
> TTD assert failed: Invalid -- JavascriptGeneratorFunction
Abort trap: 6
```

---
Couldn't found the `newly created directory`. Is not in the same directory of `app.js`

**Comment by mrkmarron** [comment]
The second command is **-TTReplay** not -TTRecord  so the command line would be: 
`node --nolazy -TTReplay:log`

**Comment by mrkmarron** [comment]
The "log" directory is created relative to the folder where the node executable binary is located.

**Comment by Josema** [comment]
Yes, now the output is correct.
```
$ /Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --nolazy -TTReplay:log
> Hello world!

Reached end of Execution -- Exiting.
```
And for the log directory:
```
$ tree log
log
├── snap_0.snp
├── src_1.js
├── src_10.js
├── src_11.js
├── src_12.js
├── src_13.js
├── src_14.js
├── src_15.js
├── src_16.js
├── src_17.js
├── src_18.js
├── src_19.js
├── src_2.js
├── src_20.js
├── src_21.js
├── src_22.js
├── src_23.js
├── src_24.js
├── src_25.js
├── src_26.js
├── src_27.js
├── src_28.js
├── src_3.js
├── src_4.js
├── src_5.js
├── src_6.js
├── src_7.js
├── src_8.js
├── src_9.js
└── ttdlog.log

0 directories, 30 files
```

And this is my setup for vscode:
```
        {
            "name": "Chakra",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/${relativeFile}",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "/Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node",
            "runtimeArgs": [
                "--nolazy",
                "--debug",
                "-TTDebug:log",
                "-TTBreakFirst" 
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole"
        },
```
This is the output when trying to run the same app.js that we used before:
```
/Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --debug-brk=4539 --nolazy --debug -TTDebug:log -TTBreakFirst ../app.js 
Error is: 87 Shared library version mismatch
Message is: Failed Read!!!
TTD assert failed: Not sure what happened
```

**Comment by mrkmarron** [comment]
Thanks, that is very helpful. @digitalinfinity and @obastemur it looks like there is an error when we try to read one of the log files -- errno is 87 and we translate this to the error message "87 Shared library version mismatch" using strerror. Is it possible that there is an incompatibility with our build and OSX El capitan v10.11.2? 

I don't have access to my mac for the next few days but would like to try and repro this. @Josema can you share the contents of your app.js?

**Comment by Josema** [comment]
@mrkmarron Is the same script that you send me before.
```
function hello() {
  var msg = 'Hello world!';
  telemetryLog(msg, true);
}

setTimeout(hello, 10);
```

But it fails with any other script.

**Comment by mrkmarron** [comment]
Interesting, can you share a script that fails when you run it?

**Comment by Josema** [comment]
I forgot to mention that the `log` directory is created on the same directory of the file where I run the script. Let's make some tests from the beginning.
I'm in this directory. `/Users/enzo/test`

This is your script called yourscript.js
```
function hello() {
  var msg = 'Hello world!';
  telemetryLog(msg, true);
}

setTimeout(hello, 10);
```
If I run it this is the output:
```
$ /Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --debug-brk=27886 --nolazy --debug -TTDebug:log -TTBreakFirst yourscript.js 
Filename: /Users/enzo/test/log/ttdlog.log
Error is: 2 No such file or directory
Message is: Failed File Open
TTD assert failed: Trying to read a invalid file.
Abort trap: 6
```

Let's try with your two commands:
```
$  /Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --nolazy -TTRecord:log yourscript.js 
Hello world!
```
The folder `log` it's been created on the same directory:
```
enzo at MacBook-Pro-2.local  ~/test
$ l
total 8
drwxr-xr-x    4 enzo  staff   136 Jan  8 14:21 .
drwxr-xr-x+ 115 enzo  staff  3910 Jan  8 14:21 ..
drwxr-xr-x   32 enzo  staff  1088 Jan  8 14:20 log
-rw-r--r--    1 enzo  staff    99 Jan  8 14:17 yourscript.js
```
Running your seccond command:
```
$ /Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --nolazy -TTReplay:log
> Hello world!

Reached end of Execution -- Exiting.
```
If I run the command that vscode generates with my setup this is the output:
```
enzo at MacBook-Pro-2.local  ~/test
$ /Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --debug-brk=27886 --nolazy --debug -TTDebug:log -TTBreakFirst yourscript.js 
Debugger listening on 127.0.0.1:27886
```
But the script never finish, is listening.

Now if I break the script and I try the same from the upper directory this happen:
```
enzo at MacBook-Pro-2.local  ~
$ /Users/enzo/.nvs/chakracore/7.0.0-pre10/x64/bin/node --debug-brk=27886 --nolazy --debug -TTDebug:log -TTBreakFirst test/yourscript.js 
Filename: /Users/enzo/log/ttdlog.log
Error is: 2 No such file or directory
Message is: Failed File Open
TTD assert failed: Trying to read a invalid file.
Abort trap: 6
```

**Comment by obastemur** [comment]
```
errno is 87 and we translate this to the error message "87 Shared library version mismatch" using strerror. Is it possible that there is an incompatibility with our build and OSX El capitan v10.11.2?
```

Latest ChakraCore, this issue should be fixed

**Comment by mrkmarron** [comment]
We have updated the TTD usage flags to be easier to use and simpler to write traces (PR #180). Our TTD documentation has also been revised (https://aka.ms/nodettd) and macOS support is improved. This should resolve the issues here but please re-open if you continue to have problems.
