### ISSUE TITLE
JSStream crash at shutdown AsyncWrap::~AsyncWrap accesses invalid Environment

### ISSUE THREAD

**Issue by ianwjhalliday** [nodejs/node-chakracore#165]
Merging a recent nodejs/node/master commit into node-chakracore brought in the refactoring of `node::StartNodeInstance` into multiple `Start()` functions to make more clearly explicit the separation between program, `Isolate`, and `Environment` initialization (https://github.com/nodejs/node/commit/ceb602326066674b894c9fc4d53166d06a918c02).

Turns out node-chakracore is cleaning up live `AsyncWrap` objects during `isolate->Dispose()`, after the `Environment` goes out of scope, which causes bad memory access violations since `~AsyncWrap()` accesses the environment.  Before the refactoring the `Environment` memory was still intact during `isolate->Dispose()` and so this did not manifest as a problem.  Now however, the `Environment` memory, since it is on the stack, is overwritten and we blow up.

Node-v8 does not have a problem because it seems to not clean up these objects on shutdown.  E.g. I see `JSStream` ctor called but the dtor is not called and the process exits.

This raises the question: is node's policy intentionally such that objects are not cleaned up before Isolate disposal at shutdown?  Correspondingly, should node-chakracore not being calling these callbacks on shutdown?

**Comment by ianwjhalliday** [comment]
Repro is to have a script that creates a `JSStream` (e.g. `test/parallel/test-async-wrap-check-providers.js`)

@trevnorris would you know if there is an expectation here?

cc @bnoordhuis who did the `node::Start` function refactoring

**Comment by bnoordhuis** [comment]
> This raises the question: is node's policy intentionally such that objects are not cleaned up before Isolate disposal at shutdown?

Yes.  V8 doesn't guarantee that destructors of weakly persistent objects (what AsyncWraps are) run before isolate termination.  As there is only one isolate and it's disposed of at program exit, node takes the easy path.

**Comment by ianwjhalliday** [comment]
> V8 doesn't guarantee that destructors of weakly persistent objects (what AsyncWraps are) run before isolate termination.

Does V8 not specify the behavior, or does it guarantee that destructors are definitely not run?  If it changed behavior in the future to run them this issue would be exposed in node-v8.

**Comment by ianwjhalliday** [comment]
Sounds like the right thing for now is for node-chakracore to not run these destructors on shutdown

**Comment by bnoordhuis** [comment]
> Does V8 not specify the behavior, or does it guarantee that destructors are definitely not run?

I wouldn't use the word "guarantee" but more than one V8 developer has said the current behavior is unlikely to change.  V8 has behaved this way since its first public release 8 or 9 nine years ago.

**Comment by ianwjhalliday** [comment]
Ok great.

I have updated node-chakracore to do the same in PR #166
