### ISSUE TITLE
Node addons

### ISSUE THREAD

**Issue by danieljoppi** [nodejs/node-chakracore#17]
Actual Node (V8) addons works with C/C++

The Node with chakra ... I can create addons using C#?

**Comment by kunalspathak** [comment]
@danieljoppi , Node with chakra relies on C/C++ just as Node(v8). For add-ons using C#, you might want to check [edge.js](https://github.com/tjanczuk/edge).

**Comment by danieljoppi** [comment]
@kunalspathak I know about [edge.js](https://github.com/tjanczuk/edge) ... but it is not a good option for my application ...
:cry:

**Comment by kunalspathak** [comment]
@danieljoppi , given that node eco system doesn't support write managed add-ons, is that ok to close the issue?
