### ISSUE TITLE
darwin missing from nightlies

### ISSUE THREAD

**Issue by williamkapke** [nodejs/node-chakracore#174]
It's there on the 13th, but not after...

[v8.0.0-nightly2017021305e0f044bc/](https://nodejs.org/download/chakracore-nightly/v8.0.0-nightly2017021305e0f044bc/)                  13-Feb-2017 10:30                   -
[v8.0.0-nightly2017021405e0f044bc/](https://nodejs.org/download/chakracore-nightly/v8.0.0-nightly2017021405e0f044bc/)                  14-Feb-2017 10:30                   -

**Comment by digitalinfinity** [comment]
Thanks @williamkapke - @joaocgreis mentioned this too a couple days ago. We're looking at the right way to fix this.

**Comment by kunalspathak** [comment]
Fixed by #185 

Latest nightly has it. 
https://nodejs.org/download/chakracore-nightly/v8.0.0-nightly2017031320fa6b1909/

**Comment by joaocgreis** [comment]
I can confirm the release job is running as expected now.
