### ISSUE TITLE
[Windows 10 IoT core] NodeJS cluster API

### ISSUE THREAD

**Issue by ghost** [nodejs/node-chakracore#179]
* **Version**: `v7.0.0-pre`
* **Platform**: `Windows 10 IoT core`
* **Subsystem**: `Raspberry Pi 3`

Hi,

I am currently playing with Windows 10 IoT Core.

I am coding a Bluetooth - Bluetooth LE scanner. The idea is to detect any BT, BTLE device close to my Raspberry Pi.

In order to do so I have created the following project: https://github.com/jackTheRipper/uwp-bluetooth-scanner

At first I developed it using the `cluster` API of Node-JS. I didn't notice that it's not supported by `ntvsiot`.

**Why the NodeJS `cluster`?**

I would like to fork workers which are watching at one specific type of devices. My master would be my web server.

**What happened?**

I used the Node `cluster` API at first but I wasn't able to run my project due to an error saying that I can't allocate more memory to my main process.

Anything planned for providing the support of the `cluster` API in `node-chakra` ?

@kunalspathak

**Comment by kunalspathak** [comment]
Thanks @jackTheRipper for reporting. Could you provide a repro code ?

**Comment by ghost** [comment]
@kunalspathak I pushed the code using the cluster here: https://github.com/jackTheRipper/uwp-bluetooth-scanner/tree/cluster-version

The program dies with the following output:

```
Exception was thrown at line 158, column 11 in Unknown script code (1)
0x80004005 - JavaScript runtime error: unknown exception
The program '[3316] backgroundTaskHost.exe' has exited with code -1073740791 (0xc0000409).
```

When debugging it breaks on the first `fork`:

```
const env = Object.assign({}, {
    MODULE_NAME: worker.name,
    MODULE_PATH: worker.module,
}, worker.env);

const w = cluster.fork(env); // here it dies
```

I don't know if it could be related, version of the OS for the Raspberry: 10.0.14393.693

**Comment by kunalspathak** [comment]
@munyirik - in case he is aware of this.

**Comment by ghost** [comment]
@kunalspathak I updated my code. The version on master using EventEmitter works like a charm.

The version with the cluster doesn't. At least on the Raspberry Pi.

Anyway super experience. Doing IoT with JavaScript !

**Comment by munyirik** [comment]
Hi @jackTheRipper if you need to use cluster I would recommend using node-chakracore. 

It looks like you're using node-chakra (uwp) which doesn't support it. There's also more things it doesn't support (listed [here](https://github.com/ms-iot/ntvsiot#unsupported-nodejs-api))

With node-chakracore you can still be able to access the UWP API for Bluetooth with [NodeRT](https://github.com/NodeRT/NodeRT)...and you will be able to use cluster.

**Comment by ghost** [comment]
Ok. Thank you. I will take a look at it. Let's close the issue then.
