### ISSUE TITLE
Runtime crash on Windows 2008 R2

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/node-chakracore#20]
The current chakracore-master build crashes on startup in Windows 2008 R2, without any warning or error.

By running in Visual Studio in debug mode, the crash seems to be triggered by an assertion failure in [CharClassifier.cpp, line 624](https://github.com/nodejs/node-chakracore/blob/8a8c98ca4b733fe23e5c921584329fd1946e51eb/deps/chakrashim/core/lib/Parser/CharClassifier.cpp#L624).

cc @nodejs/node-chakracore

**Comment by kunalspathak** [comment]
Thanks @joaocgreis  for reporting this. It is a known chakracore issue that is already fixed. See [this](https://github.com/nodejs/node-chakracore/issues/6#issuecomment-176512169) for more details. We will get those changes in node+Chakracore with next update. Workaround for now would be to install IE11 on the machine.

**Comment by joaocgreis** [comment]
Great, thanks @kunalspathak. No point in leaving this open then.

**Comment by kunalspathak** [comment]
I think we should keep this issue open till we port the changes in chakracore-master.

**Comment by ianwjhalliday** [comment]
@kunalspathak this is fixed now in https://github.com/nodejs/node-chakracore/releases/tag/node-chakracore-6.0.0-pre3 correct?

**Comment by kunalspathak** [comment]
yes, but the changes are not yet in `chakracore-master`. Once they get in, we can close the issue.

**Comment by ianwjhalliday** [comment]
Ah, gotcha
