### ISSUE TITLE
Build failure with Microsoft Visual C++ Build Tools 2015

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/node-chakracore#200]
| This issue replaces "building with Microsoft Visual C++ Build Tools 2015 Technical Preview" (https://github.com/nodejs/node-chakracore/issues/24). That issue no longer exists, most likely because the account that was used to create it was deleted (user `dn7q3b`). |
|-|

* **Version**: `xplat` at https://github.com/nodejs/node-chakracore/commit/a35216f4b237c0b0e9604fe8b3b660b47c4211f3
* **Platform**: Windows with Visual C++ Build Tools 2015
* **Subsystem**: `chakrashim`

Console output shows 30 occurrences of:

```
c:\workspace\node-compile-windows\label\win-vcbt2015\deps\chakrashim\core\lib\runtime\Base/DelayLoadLibrary.h(14): fatal error C1083: Cannot open include file: 'cor.h': No such file or directory
```

All 30 errors are in `DelayLoadLibrary`: https://github.com/nodejs/node-chakracore/blob/a35216f4/deps/chakrashim/core/lib/Runtime/Base/DelayLoadLibrary.h#L14

**Comment by digitalinfinity** [comment]
@joaocgreis the CI build does pass- https://ci.nodejs.org/view/All/job/chakracore-test-windows/46/

However, I see test failures in this log: https://ci.nodejs.org/job/node-test-binary-windows/RUN_SUBSET=3,VS_VERSION=vs2015,label=win2012r2/7288/console

Is this the same issue as nodejs/node#10286?

**Comment by joaocgreis** [comment]
That failure was with binaries compiled by VS2015, not VCBT, so it's unrelated. The failure is in `parallel/test-http-client-get-url` so it's not the same as https://github.com/nodejs/node/issues/10286, but might have the same root cause. This looks like a one off to me.

I am positive that your changes fix this issue.

**Comment by joaocgreis** [comment]
Fixed by https://github.com/nodejs/node-chakracore/pull/203
