### ISSUE TITLE
Port gyp changes to upstream

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/node-chakracore#21]
As [commented](https://github.com/nodejs/node/pull/4765#issuecomment-173091869) by @shigeki on nodejs/node#4765, we need to submit gyp changes to upstream. An equivalent patch is in PR on nodejs/node-gyp#873.

**Comment by munyirik** [comment]
The changes have been submitted - https://chromium.googlesource.com/external/gyp/+/02b145a1a4f4e1c62e8bae06045caf852d9ef17f
