### ISSUE TITLE
New contributors for Node-ChakraCore

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/node-chakracore#214]
Please add the following contributors to [node-ChakraCore](https://github.com/orgs/nodejs/teams/node-chakracore) team:

* [jasongin](https://github.com/jasongin) - Jason Ginchereau
* [MSLaguana](https://github.com/MSLaguana) - Jimmy Thomson
* [mrkmarron](https://github.com/mrkmarron) - Mark Marron

//cc: @mhdawson, @jasnell

**Comment by jasnell** [comment]
done!
