### ISSUE TITLE
TTD replay-debug broken

### ISSUE THREAD

**Issue by mrkmarron** [nodejs/node-chakracore#218]
Copying from [here](https://github.com/mrkmarron/RFSDemoJS/issues/3). From initial investigation it looks like the merge in commit ac1e9e0 altered some code that indicates if the debugger is attached and now the flag use code in node.cc (looks like lines 4856 and 4882) is out of date. 

## Setup:
MacOS Sierra 10.12.4
Node version: v8.0.0-nightly201704205bd7d4d626
VSCode version: Version 1.12.0-insider (1.12.0-insider)

## Issue:
I get `Must enable debugger if running --replay-debug.` in the debug console when trying to debug.

### Debug console:
`/Users/xxx/.nvs/nvs --debug-brk=33701 run chakracore-nightly --nolazy --break-first --replay-debug=/Users/xxx/Projects/RFSDemoJS/_diagnosticTraces/emitOnLogWarn_graceful-fs_line-78_column-13_bucket-0/trace-0 .vscode/empty.js 
Must enable debugger if running --replay-debug.
Run with "-h" for help with flags.`

**Comment by iX315** [comment]
Same issue here...
Following [THIS](https://github.com/nodejs/node-chakracore/blob/xplat/TTD-README.md)

vscode launch.json contains:
`{
            "name": "TTD - Trace Debug",
            "type": "node",
            "request": "launch",
            "protocol": "legacy",
            "stopOnEntry": true,
            "program": "${file}",
            "windows": {
                "runtimeExecutable": "nvs.cmd"
            },
            "osx": {
                "runtimeExecutable": "nvs"
            },
            "linux": {
                "runtimeExecutable": "nvs"
            },
            "runtimeArgs": [
                "run",
                "chakracore-nightly",
                "--nolazy",
                "--break-first",
                "--replay-debug=./"
            ],
            "console": "internalConsole"
        }`

### Setup
OSX 10.12.3 (16D32)
NODE (chakracore-nightly/8.0.0-nightly201704215bd7d4d626/x64)
Version 1.12.0-insider (1.12.0-insider)

### Issue
`Must enable debugger if running --replay-debug.`

**Comment by kfarnung** [comment]
@mrkmarron @iX315 I just landed TTD support using the inspector protocol this week, but there's a [node PR](https://github.com/nodejs/node/pull/12949) required to get launching with inspector working correctly.  Once that PR lands, please try again using inspector.

**Comment by kfarnung** [comment]
I just realized that you can add `--inspect-brk` to the `runtimeArgs` to work around the VS Code issue.

```
{
    "name": "TTD - Trace Debug",
    "type": "node",
    "request": "launch",
    "protocol": "legacy",
    "stopOnEntry": true,
    "program": "${file}",
    "windows": {
        "runtimeExecutable": "nvs.cmd"
    },
    "osx": {
        "runtimeExecutable": "nvs"
    },
    "linux": {
        "runtimeExecutable": "nvs"
    },
    "runtimeArgs": ["--inspect-brk", "run", "chakracore-nightly", "--nolazy", "--break-first", "--replay-debug=./"],
    "console": "internalConsole"
}
```

**Comment by mrkmarron** [comment]
TTD and inspector are now working. Further, the readme.md and example code (for the RFS demo) has been updated to work with node-chakracore/8.0.0-pre3 and resolve this issue.

**Comment by mrkmarron** [comment]
Also, setting `"protocol": "inspector"` overrides the VSCode protocol heuristic selection.
