### ISSUE TITLE
Node-ChakraCore debugging is broken

### ISSUE THREAD

**Issue by digitalinfinity** [nodejs/node-chakracore#221]
* **Version**: nightly (v8.0.0-pre)
* **Platform**: all
* **Subsystem**: debugger

Looks like the recent merge from nodejs/node master broke Node-ChakraCore since --debug is no longer supported. This should get resolved when https://github.com/nodejs/node-chakracore/pull/210 lands.

**Comment by kfarnung** [comment]
#210 landed, we'll file individual issues for anything that comes up with inspector.
