### ISSUE TITLE
Link to correct JSRT documentation

### ISSUE THREAD

**Issue by liminzhu** [nodejs/node-chakracore#23]
Consider update the JSRT link in this [paragraph](https://github.com/nodejs/node-chakracore#how-it-works) to https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview. Old link navigates to MSDN documentation of JSRT in Chakra and it has minor differences with JSRT in ChakraCore.

**Comment by kunalspathak** [comment]
Thanks @liminzhu , will do.

**Comment by kfarnung** [comment]
This has been fixed.
