### ISSUE TITLE
building with Microsoft Visual C++ Build Tools 2015 Technical Preview

### ISSUE THREAD

**Issue by dn7q3b-zz** [nodejs/node-chakracore#24]
Do you support building with [Microsoft Visual C++ Build Tools 2015 Technical Preview](https://blogs.msdn.microsoft.com/vcblog/2015/11/02/announcing-visual-c-build-tools-2015-standalone-c-tools-for-build-environments/)?

On Win 10 Pro with only the Build tools (both 8 and 10 SDKs installed) using
- Visual C++ x64 Native Build Tools Command Prompt
- added set VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
- cmd> vcbuild chakracore nosign x64

I get a bunch of failures due to missing cor.h?

Is there some way to get around this? Or is this something the team working on the standalone C++ Build Tools Preview needs to address?

First error:
`c:\dev\cygwin\home\am\node-chakracore\deps\chakrashim\core\lib\runtime\Base\DelayLoadLibrary.h(14): fatal error C1083:
Cannot open include file: 'cor.h': No such file or directory [C:\dev\cygwin\home\am\node-chakracore\deps\chakrashim\cor
e\lib\jsrt\Chakra.Jsrt.vcxproj] [C:\dev\cygwin\home\am\node-chakracore\deps\chakrashim\chakracore.vcxproj]`

```
C:\dev\cygwin\home\am\node-chakracore>vcbuild chakracore nosign x64
Looking for Visual Studio 2015
Found Visual Studio 2015
configure   --engine=chakracore --dest-cpu=x64 --tag=
ctrpp not found in WinSDK path--using pre-gen files from tools/msvs/genfiles.
creating  icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'asan': 0,
                 'host_arch': 'x64',
                 'icu_small': 'false',
                 'node_byteorder': 'little',
                 'node_enable_v8_vtunejit': 'false',
                 'node_engine': 'chakracore',
                 'node_install_npm': 'true',
                 'node_prefix': '/usr/local',
                 'node_release_urlbase': '',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_use_dtrace': 'false',
                 'node_use_etw': 'true',
                 'node_use_lttng': 'false',
                 'node_use_openssl': 'true',
                 'node_use_perfctr': 'true',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'python': 'C:\\dev\\python27\\python.exe',
                 'target_arch': 'x64',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 0,
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0}}
```

**Comment by kunalspathak** [comment]
@dn7q3b , this is known problem and related to windows 8.1 SDK header dependencies of chakracore. Unfortunately you will need to install VS 2013 or VS 2015 for now to address it until we work on removing the dependency. Feel free to open an issue on Microsoft/Chakracore.

**Comment by orangemocha** [comment]
We should keep this issue open until the problem is resolved...

**Comment by joaocgreis** [comment]
This issue was unavailable on GitHub for some time, and was replaced by https://github.com/nodejs/node-chakracore/issues/200. It is now solved.
