### ISSUE TITLE
Latest test-addon-napi test failing with node-chakracore

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/node-chakracore#246]
Below 3 addon-napi test cases are failing. This issue is to track the fix and re-enable them.

```cmd
test/addons-napi/test_async/test.js
test/addons-napi/test_make_callback_recurse/test.js
test/addons-napi/test_reference/test.js
```

* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by kunalspathak** [comment]
@jasongin  - I think your PR still doesn't address `test/addons-napi/test_reference/test.js`, right?

**Comment by jasongin** [comment]
Right, reopening to track the remaining test_reference failure. For that I'll make a PR to node/master and we should re-enable the test when we merge the fix.

**Comment by kunalspathak** [comment]
Great, Thanks!

**Comment by kfarnung** [comment]
I'll take a look.
