### ISSUE TITLE
npm does not work in latest nightly

### ISSUE THREAD

**Issue by alexlamsl** [nodejs/node-chakracore#251]
* **Version**: v8.0.0-nightly20170520b60c0243d4
* **Platform**: Windows 8 x64
* **Subsystem**: npm

```
>npm install
npm ERR! fetch failed https://registry.npmjs.org/param-case/-/param-case-2.1.1.tgz
npm WARN retry will retry, error on last attempt: TypeError: Object doesn't support property or method 'asyncReset'
```

**Comment by alexlamsl** [comment]
Not sure if related: https://github.com/nodejs/node/issues/13045

**Comment by alexlamsl** [comment]
Going back day-by-day, the last working version is `v8.0.0-nightly2017051728cdc33c8d`

**Comment by addaleax** [comment]
> Not sure if related: nodejs/node#13045

Sounds a lot like it – Can you check that applying https://github.com/nodejs/node/commit/6bfdeedce5529810dbe7c61bd712fc50174a19f1 helps?

**Comment by alexlamsl** [comment]
@addaleax thanks for the information.

I don't have the environment to compile Node.js though, so I guess I'll wait :sweat_smile:

**Comment by sebdeckers** [comment]
@addaleax That fixed it for me, thanks!

**Comment by digitalinfinity** [comment]
Thanks @addaleax - we ran into this too, and the PR from @refack seemed to address this (thanks @refack!). @kunalspathak FYI, nodejs/node#13092 has landed.

**Comment by alexlamsl** [comment]
No longer an issue with `chakracore 8.0.0-pre3` - thanks!
