### ISSUE TITLE
Nomenclature of branches in node-chakracore

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/node-chakracore#275]
In order to match the work being done in various branches of `node-chakracore` repo, we are proposing to rename our current branches. This will be done by end of day 06/01/2017 PST.

* [xplat](https://github.com/nodejs/node-chakracore/commits/xplat) will be renamed to `master`. This will be made **default** branch of `node-chakracore` repo. This branch will be tracking `master` branch of `nodejs/node` repo and will have stable chakracore from `Microsoft/chakracore`.

* [master](https://github.com/nodejs/node-chakracore/commits/master) will be renamed to `nodejs-master`. This branch will track the latest commit that was merge in `master` (old `xplat`) branch. Every time we merge a commit from upstream, this branch will be updated.

* [chakracore-master](https://github.com/nodejs/node-chakracore/commits/chakracore-master) - This will be unchanged. This branch will contain node/chakrashim changes from `master` (old `xplat`) branch and that from `master` branch of `Microsoft/Chakracore`.

Please let us know if anyone has objections to this.  

cc: @nodejs/node-chakracore 

* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by kunalspathak** [comment]
@joaocgreis  - Once this is done, we will have to update the nightly CI job to target the `master` branch instead of `xplat`.

**Comment by joaocgreis** [comment]
@kunalspathak ok, let me know when to change it.

**Comment by kunalspathak** [comment]
@joaocgreis  - I have pushed new branches but left the `xplat` branch as it is. Once you change the CI job, i will delete this branch.

**Comment by joaocgreis** [comment]
@kunalspathak done, the next nightly will come from the master branch.

**Comment by kunalspathak** [comment]
Thanks @joaocgreis . I have deleted `xplat` and `xplat-v8.x` branches.
