### ISSUE TITLE
TTD: Emit on SIGINT not working

### ISSUE THREAD

**Issue by mrkmarron** [nodejs/node-chakracore#279]
* **Version**: node-chakracore 8.0.0-pre3
* **Platform**: Windows
* **Subsystem**: TTD

It looks like some merge disconnected the logic in lib/internal/process.js (line 238). This was a bit of an odd implementation so we should (1) also see if there is a preferable way to do it and (2) we might also want to make it catch SIGTERM too.

**Comment by kfarnung** [comment]
@mrkmarron I tested on Windows and I think it's working for me:

```
E:\GitHub\node-chakracore2 [ttdsigint]> .\Debug\node.exe --record D:\Samples\HelloNode\built\server.js
Recording is enabled (but not yet started)...
Server running at http://127.0.0.1:8000/
Recording started (after main module loaded)...
    Write error trace to: D:\Samples\HelloNode\built\_diagnosticTraces\emitOnSigInt
```

I hit Ctrl-C and it output the trace successfully.  This sample uses an HTTP server, so it was just idling at the point I hit Ctrl-C.  For your repro did you use a long-running JS loop?

**Comment by mrkmarron** [comment]
I just tried to repro and it works fine for me as well. It is possible that I was doing something strange. I'll close this for now and keep an eye on it.
