### ISSUE TITLE
Update contribution guidelines for javascript and C++ files

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/node-chakracore#28]
As per https://github.com/nodejs/node-chakracore/pull/25#commitcomment-16192924 , we should update contribution guidelines to reflect the naming and coding convention that are followed in chakrashim of node+chakracore. Node sources, should continue to follow the conventions as per nodejs/node.

**Comment by orangemocha** [comment]
Isn't code in chakrashim considered a dependency that we take as a whole and don't modify here? I feel that it if those conventions should be documented it would be in the https://github.com/Microsoft/ChakraCore repo.

**Comment by kunalspathak** [comment]
True that chakrashim is a dependency, but it doesn't come from any repo.  is updated directly in this repo. May be if we move chakrashim in its own repo we can move these contribution guidelines with it. Till then we can have it here, if someone wants to update shim.

'Chakracore' is a dependency that directly come as it is from Microsoft/Chakracore and we definitely don't want it's contribution guidelines here.

Sent from Outlook Mobilehttps://aka.ms/blhgte

**Comment by kfarnung** [comment]
Our current contribution guidelines require the Node.js guidelines to be followed in chakrashim.
