### ISSUE TITLE
new Date().toLocaleDateString() invalid result

### ISSUE THREAD

**Issue by BobFrankston** [nodejs/node-chakracore#281]
Microsoft Windows [Version 10.0.14393

{ http_parser: '2.7.0',
  node: '7.0.0-pre8',
  chakra: '11.0.14393.1198',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '48',
  openssl: '1.0.2h' }

As per below toLocalDateString() is returning the 0x200e character instead of the space character

```
  var dd = new Date().toLocaleDateString()
 for(var dc of dd) console.log(dc.charCodeAt().toString(16))
200e
36
200e
2f
200e
31
200e
2f
200e
32
30
31
37
```

**Comment by digitalinfinity** [comment]
Thanks @BobFrGit - I can repro this in ch (ChakraCore's standalone host too). If you don't mind- can you open this issue on Microsoft/ChakraCore instead? If not, I'm happy to open one on your behalf.

Also, curious- is this node-chakra that you're using or node-chakracore?

**Comment by BobFrankston** [comment]
I wasn’t sure where to report the bug so I’m open up to better suggestions and a URL. Glad to have you do it.

 

The bug appeared when I upgraded nodejs from the nodejs.org site to 8.0. It seems that a byproduct was to remove the old NodeJS including its position in the path and then reinstall which left it at the end of the path list. It took me a while to figure out the source of the bug – switching the execution engine. 

 

As to which node – it’s whatever I get when I use the node that installed as a byproduct of NodeJSUwp for Windows IoT. I’ve since switched to using node on Linux because it is far simpler. And it seems as if the UWP stuff hasn’t be updated for VS 2017. But that’s a topic in its own right.

 

Bob Frankston

 <http://Frankston.com> http://Frankston.com

@BobFrankston

**Comment by digitalinfinity** [comment]
Thanks @BobFrGit - I've opened https://github.com/Microsoft/ChakraCore/issues/3091 to track this. Re the NodeJsUwp questions, @aruneshchandra or @munyirik might be able to help you.

**Comment by digitalinfinity** [comment]
@BobFrGit just a heads up, there is a discussion going on at https://github.com/Microsoft/ChakraCore/issues/3091 and they'd like to learn more about what you're trying to do. Feel free to chime in on that thread.

**Comment by kfarnung** [comment]
@munyirik Is there any update on NodeJsUwp and VS2017 support?

**Comment by munyirik** [comment]
Sorry, no update at this time.

cc. @paulmon @msalehmsft

**Comment by digitalinfinity** [comment]
Closing since Microsoft/ChakraCore#3091 is closed
