### ISSUE TITLE
Node ChakraCore collaborators sync-up

### ISSUE THREAD

**Issue by thefourtheye** [nodejs/node-chakracore#29]
As we have new people from both the worlds (Node.js and Chakra), I feel that it would be better to have a meeting to sync up on the processes followed, preferred communication channel and other stuff. Also it would give us a chance to introduce ourselves to the team. Thoughts cc @nodejs/node-chakracore

**Comment by orangemocha** [comment]
Sounds good to me. Hopefully we can find a time that works for every one, as apparently we have people all over the world. 

Here's a doodle: http://doodle.com/poll/hdtfawcbpymchrf7

**Comment by orangemocha** [comment]
@thefourtheye do any of the times in the doodle work for you?

**Comment by thefourtheye** [comment]
Oops, I am sorry. I think I forgot to press the save button there. My choices are properly listed now.

**Comment by orangemocha** [comment]
Great, we have one time slot (out of 100 options :smile: ) that works for all poll participants. 

@nodejs/node-chakracore, see you this Friday, February 26th, at 5pm UTC, or in your time zone: http://www.timeanddate.com/worldclock/fixedtime.html?msg=node-chakracore+WG+kickoff+meeting&iso=20160226T17&p1=1440

I will post hangout links by Friday.

Please suggest agenda items by commenting on this issue, or tagging existing issues/PRs with the `wg-agenda` label.

**Comment by orangemocha** [comment]
Suggested agenda items so far:
- Meet and greet
- High-level sync up on the objectives of this project.
- doc: contribution guidelines for node-chakracore [https://github.com/nodejs/node-chakracore/pull/27 ]
- Update contribution guidelines for javascript and C++ files [https://github.com/nodejs/node-chakracore/issues/28]
- Managing this repository with Git towards the PR at the end [https://github.com/nodejs/node-chakracore/issues/31]

**Comment by orangemocha** [comment]
Hangout on Air links:
- For participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYfwFduJWygz18lncv0WN7CXDaRPoKqWjLUc-E6SVFBHWgjgZw?hl=en&authuser=0
- For viewers: http://www.youtube.com/watch?v=9SdBbUrmWeM

**Comment by joaocgreis** [comment]
I'd like to add https://github.com/nodejs/node-chakracore/issues/31 to the agenda.

**Comment by orangemocha** [comment]
I summarized today's discussion in this doc: https://docs.google.com/document/d/1USCqsrat0QM0H4EMrutb_slmAHAkja-z4cQ2gPlc-Pg/edit?usp=sharing

This is the same doc shared with participants, so feel free to make any edits. Thank you!
