### ISSUE TITLE
Investigate test-inspector-exception failure

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/node-chakracore#306]
* **Version**:
* **Platform**:
* **Subsystem**:

As part of 4f8f708db2722ce828406127862498216bb2e060 `test-inspector-exception` was failing. I have marked it as flaky for now.

**Comment by kfarnung** [comment]
@kunalspathak It's already fixed in https://github.com/nodejs/node-chakracore/commit/7517f978cc3827613be89cd6dffc2ba02e2e033b, you should be able to just cherry-pick the change.
