### ISSUE TITLE
A Question regarding HandleScope imlementation

### ISSUE THREAD

**Issue by KobyBo** [nodejs/node-chakracore#311]
Hi
First of all I think this is an awesome project :)
Coming from the v8 API, I was interested to see ChakraCore's API. I went through some of the implementation, looking at the differences between the two engines. One thing I'm not sure I understand is the HandleScope:
1. According to the documentation in v8.h, and [here ](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview), ChakraCore's GC scans the stack looking for references. So, if v8::Local instances are supposed to be stack allocated, why is it not enough to just hold the JsValueRef as a member of the Local class and that's it?
2. If JsValueRefs are stored either in the local array or in the js array, why is it needed to also call JsAddRef (thus needing to store them in another list)?

Thanks :)

**Comment by jianchun** [comment]
1. I recall the (rare) scenario that forced us to do it this way was:
```c++
HandleScope scope(...);
Local<Value>* args = new Local<Value>[4];
args[0] = Local<Value>::New(...);
args[1] = Local<Value>::New(...);
...
SomeFunc(args);
```
All these `Local`s are allocated in heap so its members are not scanned by GC. We had to track them in `HandleScope` to avoid them being collected by GC.

2. That is a last fallback if local array is full and js array creation fails (e.g. the host is currently in disabled or exception state, or engine has run into memory limit set by host).
