### ISSUE TITLE
Not compatible with v8 nodejs packages (pre5)

### ISSUE THREAD

**Issue by feng-xiao** [nodejs/node-chakracore#32]
got following error when running gulp tasks

(node:26596) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

**Comment by rvagg** [comment]
this is a warning that will go away when the dependencies of gulp or the tasks they are running upgrade graceful-fs to the latest version, you could assist this by figuring out what is using graceful-fs and go ask them to update to the latest version

**Comment by feng-xiao** [comment]
have you tested it with gulp-msbuild? in which case, it failed besides showing the same warning

**Comment by jianchun** [comment]
@feng-xiao Thanks for reporting this! I reproduced and opened a new issue for it.
