### ISSUE TITLE
Publish Node-ChakraCore release builds on nodejs.org

### ISSUE THREAD

**Issue by jasongin** [nodejs/node-chakracore#324]
@kunalspathak and @joaocgreis are already working on this as of a few days ago. I didn't see a tracking issue yet though.

For a few months, the recommended way to install Node-ChakraCore builds has been via `nvs`. That tool calls the GitHub API to find what releases are published, and get URIs to download the release binaries. But use of the GitHub API from CI systems is problematic, because they easily bump into GitHub's rate-limiting. A way to avoid the rate-limiting is to authenticate requests using a GitHub PAT, and `nvs` supports that, but then it's a challenge to supply the token in a secure way because CI systems don't support encrypted variables when building forks/PRs.

A straightforward way to resolve all these issues could be to publish Node-ChakraCore release builds to nodejs.org, in another directory, similar to how nightly builds are already published there.

**Comment by jasongin** [comment]
See also https://github.com/sass/node-sass/pull/1777

**Comment by jasongin** [comment]
If releases are published on nodejs.org, that would also mean that you could install Node-ChakraCore builds using `nvm` by setting `NVM_NODEJS_ORG_MIRROR` to point to the 'chakracore' subdirectory. (And maybe some other version-manager tools support similar overriding of the source URI). That would be fine for CI systems. However for actual users installing Node-ChakraCore, `nvs` would still provide a better experience since it is actually aware of the different forks.

**Comment by ghost** [comment]
@jasongin : for info this command `NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/chakracore-nightly/ nvm i node` already works with `nvm`

Source: https://gist.github.com/chicoxyzzy/77dcbf21485d80b3ad870ed0d3286579

**Comment by xzyfer** [comment]
This is true for nightlies but not for stable which are the important releases.

**Comment by ghost** [comment]
Oh yes true

**Comment by kunalspathak** [comment]
We started having `chakracore-release` builds on https://nodejs.org/download/chakracore-release/ . Thanks @joaocgreis  for helping out.
