### ISSUE TITLE
Implement hasOwnProperty for napi-addons

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/node-chakracore#331]
In 05d537e5d4037f348ad2c1c3f43309ce75c82ba4 , `test_object` was disabled because in upstream a new NAPI API  `hasOwnProperty` was added and JSRT doesn't have native support for it. One option is to use the implementation of chakrashim but I am hesitant to use it as we want to move away from chakrashim in future and have less dependency of jsrt napi on chakrashim. This issue is to track the right approach we should be taking and enable `test_object` for this repo.

**Comment by kunalspathak** [comment]
//cc : @jasongin

**Comment by kfarnung** [comment]
I'm taking a look at this. The implementation looks straight-forward.

**Comment by kfarnung** [comment]
This was fixed in https://github.com/nodejs/node-chakracore/commit/7784b248eae32e24bb867900f1395bae6e024ca9
