### ISSUE TITLE
Object keys should never sort dependent on if the qualifier has a numerical value.

### ISSUE THREAD

**Issue by restarian** [nodejs/node-chakracore#333]
Object qualifiers are linked, consistent and iterated upon in ecma. Logically, Object key order should never change dependant on numerical value. Index value re-ordering is one of those annoying functionalities in C/C++ that javascript should be blanketing. The specification needs to change here. I would be thrilled to see this happen with chakra. 

Sharpen your swords here -->
[The debate](https://stackoverflow.com/questions/3186770/chrome-re-ordering-object-keys-if-numerics-is-that-normal-expected)

**Comment by digitalinfinity** [comment]
@restarian sorry, missed this issue somehow- can you please move this issue to https://www.github.com/Microsoft/ChakraCore, that's the right place to discuss this
