### ISSUE TITLE
chakrashim: do we really need time.cpp?

### ISSUE THREAD

**Issue by obastemur** [nodejs/node-chakracore#338]
See https://github.com/nodejs/node-chakracore/pull/328#pullrequestreview-50157204

**Comment by MSLaguana** [comment]
Right now ChakraCore uses functionality from time.cpp in a bunch of different places, so removing it would be non-trivial.

**Comment by obastemur** [comment]
Closing it. Thought the link you have shared as a part of Chakrashim... We can't use that. (it's under the core and has set of other deps)

Edited: the text inside the parenthesis.
