### ISSUE TITLE
Request to add new memebers to Node-ChakraCore team

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/node-chakracore#361]
Please add @jackhorton to @nodejs/node-chakracore 

//cc: @jasnell

**Comment by digitalinfinity** [comment]
Piggy-backing on this issue- can we also get @mike-kaufman added to @nodejs/node-chakracore please?

**Comment by cjihrig** [comment]
I have invited @jackhorton and @mike-kaufman to the team.

**Comment by aruneshchandra** [comment]
Thanx @cjihrig!
