### ISSUE TITLE
Node-ChakraCore inspector incorrectly reports parent module as '.' instead of '<inspector console>'

### ISSUE THREAD

**Issue by jackhorton** [nodejs/node-chakracore#362]
* **Version**: Node-ChakraCore/master
* **Platform**: Windows (likely x-plat)
* **Subsystem**: Inspector

The test added [here](https://github.com/nodejs/node/commit/5fd2f03b16bfd6730fe82dc3217f1d05131b9615#diff-b65e0cbd060a7853beafa67e48d03b7dR317) shows this issue. Essentially, when calling require from an inspector expression, the required module's parent should have the id `'<inspector console>'` rather than what we currently print out, `'.'`. @kfarnung found that the id '.' is only added for the "main" module, or the file given to node on the command line. We correctly print the other special cases of this when the main module is the repl or a `node -e` evaluation.

**Comment by MSLaguana** [comment]
It looks like this issue is causing our CI to fail. Since it is known, should we mark the test as flaky until it is fixed?

**Comment by kfarnung** [comment]
@jackhorton and I discussed doing the workaround which is to have it check for `'.'` when run against ChakraCore, it doesn't look like that happened.

**Comment by jackhorton** [comment]
Sorry about that, I forgot to commit the change. Just fully synced, made sure the change was there, rebuilt and retested locally and everything should be back to normal now.

**Comment by kfarnung** [comment]
This was fixed in c8e6e2fe8ec7c0caf1752156e59c78ac1ad0dfc1
