### ISSUE TITLE
eslint does not work on ChakraCore

### ISSUE THREAD

**Issue by alexlamsl** [nodejs/node-chakracore#38]
So the issue is some V8-specific hack which I've narrowed down to https://github.com/sindresorhus/callsites/issues/3

**Comment by alexlamsl** [comment]
In case the issue gets edited or deleted, here's the workaround:

```
'use strict';
module.exports = function () {
    return new Error().stack.split(/\n/).slice(1).map(function(line) {
        var filename = line.match(/\((.*?)\:[0-9]+\:[0-9]+\)/)[1];
        return {
            getFileName: function() {
                return filename;
            }
        };
    });
};
```

**Comment by jianchun** [comment]
@alexlamsl Thanks for reporting and tracking down this issue!

I just did an experiment and noticed nodejs source uses config file `.eslintrc`, not `.eslintrc.js`.
- If I use `.eslintrc` and run eslint on node-chakracore, it works for me.
- If I rename `.eslintrc` to `.eslintrc.js`, eslint fails on both node-chakracore and official nodejs (v8).

On official nodejs:

```
PS D:\tmp> node -pe "process.versions"
{ http_parser: '2.6.0',
  node: '5.1.0',
  v8: '4.6.85.31',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2d' }
PS D:\tmp> node .\node_modules\eslint\bin\eslint.js tmp.js

D:\tmp\tmp.js
   1:1   error  Use the global form of 'use strict'                     strict
   1:1   error  Definition for rule 'new-with-error' was not found      new-with-error
   3:36  error  Unexpected space before function parentheses            space-before-function-paren
   9:34  error  Unexpected space before function parentheses            space-before-function-paren
  10:1   error  Expected indentation of 2 space characters but found 0  indent
  11:5   error  Expected indentation of 2 space characters but found 4  indent
  12:2   error  Newline required at end of file but not found           eol-last

✖ 7 problems (7 errors, 0 warnings)

PS D:\tmp> mv .\.eslintrc .\.eslintrc.js
PS D:\tmp> node .\node_modules\eslint\bin\eslint.js tmp.js
Cannot read config file: D:\tmp\.eslintrc.js
Error: Unexpected token ILLEGAL
SyntaxError: Cannot read config file: D:\tmp\.eslintrc.js
Error: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at module.exports (D:\tmp\node_modules\require-uncached\index.js:14:12)
    at loadJSConfigFile (D:\tmp\node_modules\eslint\lib\config\config-file.js:157:16)
    at loadConfigFile (D:\tmp\node_modules\eslint\lib\config\config-file.js:197:22)
```

Now on node-chakracore:

```
PS D:\tmp> node -pe "process.versions"
{ http_parser: '2.6.2',
  node: '6.0.0-pre5',
  chakracore: '1.1.0.4',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '47',
  openssl: '1.0.2f' }
PS D:\tmp> node .\node_modules\eslint\bin\eslint.js tmp.js
Cannot read config file: D:\tmp\.eslintrc.js
Error: Object doesn't support property or method 'getFileName'
TypeError: Cannot read config file: D:\tmp\.eslintrc.js
Error: Object doesn't support property or method 'getFileName'
   at module.exports (D:\tmp\node_modules\caller-path\index.js:5:2)
   at module.exports (D:\tmp\node_modules\require-uncached\index.js:11:2)
   at loadJSConfigFile (D:\tmp\node_modules\eslint\lib\config\config-file.js:157:9)
   at loadConfigFile (D:\tmp\node_modules\eslint\lib\config\config-file.js:197:13)
   at load (D:\tmp\node_modules\eslint\lib\config\config-file.js:437:9)
   at loadConfig (D:\tmp\node_modules\eslint\lib\config.js:67:13)
   at getLocalConfig (D:\tmp\node_modules\eslint\lib\config.js:129:9)
   at Config.prototype.getConfig (D:\tmp\node_modules\eslint\lib\config.js:223:9)
   at processText (D:\tmp\node_modules\eslint\lib\cli-engine.js:155:5)
   at processFile (D:\tmp\node_modules\eslint\lib\cli-engine.js:227:9)
PS D:\tmp> mv .\.eslintrc.js .\.eslintrc
PS D:\tmp> node .\node_modules\eslint\bin\eslint.js tmp.js

D:\tmp\tmp.js
   1:1   error  Use the global form of 'use strict'                     strict
   1:1   error  Definition for rule 'new-with-error' was not found      new-with-error
   3:36  error  Unexpected space before function parentheses            space-before-function-paren
   9:34  error  Unexpected space before function parentheses            space-before-function-paren
  10:1   error  Expected indentation of 2 space characters but found 0  indent
  11:5   error  Expected indentation of 2 space characters but found 4  indent
  12:2   error  Newline required at end of file but not found           eol-last

✖ 7 problems (7 errors, 0 warnings)
```

But both work with `.eslintrc`. With `.eslintrc.js` the failure stacks are different, though both were from `loadJSConfigFile`. 

Is there a versioning problem between your test and mine?

I do recall seeing a compat issue related to your post somewhere else. ChakraCore's `Error.stack` is a string, V8's is an array, thus usage may be incompatible without workaround like your post. Another way to capture a compatible stackframe array:

```
var err = new Error();  
Error.captureStackTrace(err);
err.stack
```

**Comment by alexlamsl** [comment]
I think `new Error().stack` is a string in V8 as well. The difference here is that the module in question intercepted [`Error.prepareStackTrace`](https://github.com/sindresorhus/callsites/blob/master/index.js#L4) which is probably something V8 uses internally to build the string.

**Comment by alexlamsl** [comment]
`.eslintrc.js` is what `eslint --init` gave me.

And I can see why `.eslintrc` might not give the same trouble - as that's probably JSON, it doesn't need the "uncached require" trick it uses in `.eslintrc.js`

**Comment by targos** [comment]
The `.eslintrc` file of node is written in YAML, so if we change its name, it should be `.eslintrc.yml`

**Comment by alexlamsl** [comment]
@targos didn't know - thanks for the clarification.

**Comment by jianchun** [comment]
> I think new Error().stack is a string in V8 as well. The difference here is that the module in question intercepted Error.prepareStackTrace which is probably something V8 uses internally to build the string.

Exactly the same fragment and the change I suggested here: https://github.com/tjanczuk/edge/pull/397/files#diff-0e4e1133adcfe5f0ff191a127128f9ceL71

ChakraCore doesn't support a hook for `new Error().stack`. `Error.captureStackTrace(err)` allows us a hook opportunity to support v8 style stack frames.

**Comment by alexlamsl** [comment]
@jianchun eh?! I'm using node-chakracore pre-5 and the workaround I posted above works...?

The [original code](https://github.com/sindresorhus/callsites/blob/master/index.js) is the one that breaks atm.

**Comment by alexlamsl** [comment]
Got out of bed and onto my PC just to be extra sure...

```
> process.versions
{ http_parser: '2.6.2',
  node: '6.0.0-pre5',
  chakracore: '1.1.0.4',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '47',
  openssl: '1.0.2f' }
> new Error().stack
'Error\n   at Global code (repl:1:1)\n   at defaultEval (repl.js:262:11)\n   at bound (domain.js:281:5)\n   at runBound (domain.js:294:5)\n   at Anonymous function (repl.js:427:7)\n   at emitOne (events.js:96:7)\n   at emit (events.js:183:7)\n   at Interface.prototype._onLine (readline.js:216:5)\n   at Interface.prototype._line (readline.js:555:3)\n   at Interface.prototype._ttyWrite (readline.js:832:9)'
```

**Comment by jianchun** [comment]
> .eslintrc.js is what eslint --init gave me.

I see, now I can reproduce the issue you reported. (In my previous test I copied .eslintrc from nodejs source.)

Will try find what we can do. This issue is from dependency on v8's Error.stack capture internals. People swaps `Error.prepareStackTrace` to get raw non-stringified `Error.stack`.

**Comment by alexlamsl** [comment]
@jianchun that's my understanding as well - glad we are on the same page :wink: 

For the record, I am not in a hurry either way - I was learning about eslint when I stumpled upon this issue. And I will be perfectly content to use `.eslintrc` instead now that I know about it.

So just typing up a record here, that's all.
