### ISSUE TITLE
Perf: Improve handling of external data

### ISSUE THREAD

**Issue by digitalinfinity** [nodejs/node-chakracore#384]
This likely needs a corresponding ChakraCore issue

**Comment by matthargett** [comment]
details?

**Comment by digitalinfinity** [comment]
@matthargett our current implementation of external object handling in the ChakraShim has a fair bit of overhead because of how ChakraCore's support for external objects is implemented. For one, the ChakraCore implementation expects that external data can only be associated with a special type of object, which means that on the shim side, we can require multiple levels of indirection and property lookups in order to get to that external data. This is problematic since Node uses external data quite heavily.

@obastemur is currently looking at improving this- coincidentally, he just opened his proposed PR yesterday at https://github.com/Microsoft/ChakraCore/pull/3639 so if you have more questions about the PR, feel free to chime in there 😄

**Comment by obastemur** [comment]
ATM there is not much to gain from external data native support. JsrtObjectWithExternalData is sufficient enough. Once node-chakracore moves to ChakraCore/master, it will start benefiting from property strings hence things will end up better for templates. There are also couple of unmerged changes waiting for ChakraCore master branch to come. Closing this one.
