### ISSUE TITLE
Debug doesn't work with `--replay-debug`.

### ISSUE THREAD

**Issue by Rokt33r** [nodejs/node-chakracore#389]
* **Version**: v8.2.1
* **Platform**: macOS Sierra 10.12.6 Darwin 16.7.0 
* **Subsystem**:

If I give `--replay-debug=./` option, debugging doesn't work

launch.json:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Trace Debug",
      "type": "node",
      "request": "launch",
      "stopOnEntry": true,
      "program": "${workspaceRoot}/src/index.js",
      "windows": { "runtimeExecutable": "nvs.cmd" },
      "osx": { "runtimeExecutable": "nvs" },
      "linux": { "runtimeExecutable": "nvs" },
      "runtimeArgs": [
        "run",
        "chakracore",
        "--nolazy",
        "--break-first",
        "--replay-debug=./"
      ],
      "console": "internalConsole"
    }
  ]
}
```

Error:
```
Debugging with inspector protocol because Node.js v8.4.0 was detected.
/Users/junyoungchoi/.nvs/nvs --inspect=46588 --debug-brk run chakracore --nolazy --break-first --replay-debug=./ src/index.js 
Starting replay/debug using log in ./
Failed to open file ./ttdlog.log
Error is: 2 No such file or directory
```

If I create `ttdlog.log` manually, it throws another error.

```
Debugging with inspector protocol because Node.js v8.4.0 was detected.
/Users/junyoungchoi/.nvs/nvs --inspect=44931 --debug-brk run chakracore --nolazy --break-first --replay-debug=./ src/index.js 
Starting replay/debug using log in ./
Failed read from stream!!!Error is: 0 Undefined error: 0
```

**Comment by kfarnung** [comment]
Are you trying to use the [TTD](https://github.com/nodejs/node-chakracore/blob/master/TTD-README.md) functionality of node-chakracore?  In that case you would have already run the application using the `--record` argument to generate the log file and then the `--replay-debug` argument to replay the recorded session.

If you're just trying to debug normally then you don't need that argument at all, the `--inspect` argument is already being provided by VS Code.

**Comment by Rokt33r** [comment]
Thanks! Yes, you're right. 

Now I've got have another problem, when I click step back or reverse button, debugger is terminated without any message.

**Comment by Rokt33r** [comment]
Seem there is an issue already you've made.
https://github.com/nodejs/node-chakracore/issues/266

**Comment by kfarnung** [comment]
Hmm, that issue doesn't look quite the same, @Rokt33r could you please open a new issue with as many details as possible about the repro?  It sounds like node is exiting when you try to step back, that's not what #266 was seeing.
