### ISSUE TITLE
Missing vcvarsall.bat.

### ISSUE THREAD

**Issue by jdalton** [nodejs/node-chakracore#4]
I'm trying to follow the [build instructions](https://github.com/Microsoft/node#how-to-build).

I'm on Windows 10 Build 10586.36 and have installed [Python 2.711](https://www.python.org/downloads/release/python-2711/), [Node v5](https://nodejs.org/dist/v5.3.0/node-v5.3.0-x64.msi), and both [Visual Studio Community](https://go.microsoft.com/fwlink/?LinkId=691978&clcid=0x409) and [Visual Studio Enterprise Trial](https://go.microsoft.com/fwlink/?LinkId=691979&clcid=0x409) (the [readme](https://github.com/Microsoft/node/blob/chnext/README.md#how-to-build) should specify which is required)

I restarted and tried 

``` bash
node>vcbuild chakra nosign x64
```

Then got

``` bash
Looking for Visual Studio 2015
Looking for Visual Studio 2013
Failed to find Visual Studio installation
```

My environment variable `%VS140COMNTOOLS%` is set but the file at `%VS140COMNTOOLS%\..\..\vc\vcvarsall.bat` is missing.

**Comment by jdalton** [comment]
I tried on a different system with Windows 10 Build 10586.36 and got the same issue. Is the readme missing a step or requirement? This time around I installed Visual Studio Community and not Visual Studio Enterprise Trial.

**Comment by kunalspathak** [comment]
@jdalton , When you installed VS, did you selected below?
- Programming Language -> Visual C++ -> Common Tools for Visual C++ 2015
- Windows and Web Deployment -> Universal Windows App Development Tools -> Tools (1.2) and Windows 10 SDK (10.0.10586)
- Windows and Web Deployment -> Universal Windows App Development Tools -> Windows 10 SDK (10.0.10240)

**Comment by jdalton** [comment]
> When you installed VS, did you selected below?

No I didn't, I was trying to follow the perquisite steps so just installed with default settings.
If something more is required we should document it.  I can create a PR.

**Comment by kunalspathak** [comment]
Did it work after selecting those options that I suggested?

> I can create a PR.

Sounds good.

**Comment by kfarnung** [comment]
v0.12 is no longer supported.  If you're seeing any issues on a recent version, please open a new issue.
