### ISSUE TITLE
build: execute fail with `Abort trap: 6` in macOS with Xcode 9

### ISSUE THREAD

**Issue by tommyZZM** [nodejs/node-chakracore#403]
* **Version**: v8.2.1
* **Platform**: macOS 10.12.6 
* **Build Enviroment**: Xcode 9 ; Apple LLVM 9.0
* **Subsystem**: -

build success without any error. but some wrannings
but start `./node` fail with `Abort trap: 6` 
after update to Xcode 9

```
./node
> Abort trap: 6
```

**Comment by tommyZZM** [comment]
also tried to build with xcode, and got this in debug navgatior

##### Thread 1 > 0 ReportFatalException
```
node`ReportFatalException:
    0x1007ab1d0 <+0>:  pushq  %rbp
    0x1007ab1d1 <+1>:  movq   %rsp, %rbp
    0x1007ab1d4 <+4>:  callq  0x100570220               ; PAL_IsDebuggerPresent
    0x1007ab1d9 <+9>:  testl  %eax, %eax
    0x1007ab1db <+11>: jne    0x1007ab1f0               ; <+32>
    0x1007ab1dd <+13>: callq  0x100585050               ; GetCurrentProcess
    0x1007ab1e2 <+18>: movl   $0x40010004, %esi         ; imm = 0x40010004 
    0x1007ab1e7 <+23>: movq   %rax, %rdi
    0x1007ab1ea <+26>: popq   %rbp
    0x1007ab1eb <+27>: jmp    0x100586b10               ; TerminateProcess
->  0x1007ab1f0 <+32>: ud2   
    (Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    0x1007ab1f2 <+34>: nopw   %cs:(%rax,%rax)
```

**Comment by digitalinfinity** [comment]
@obastemur can you help with this plase? @tommyZZM do you have the stack for when ReportFatalException is called? If so, can you share that please?

**Comment by obastemur** [comment]
https://github.com/Microsoft/ChakraCore/pull/3799
https://github.com/Microsoft/ChakraCore/pull/3806

to fix this issue.

**Comment by obastemur** [comment]
Please update to latest ChakraCore to fix this problem. /cc @digitalinfinity @MSLaguana

**Comment by obastemur** [comment]
This should be fine now. @tommyZZM Thanks for reporting!
