### ISSUE TITLE
REPL broken for async function 

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/node-chakracore#41]
REPL for Node-ChakraCore does not work with async functions.

Node-Chakra version
`v6.0.0-pre4`

```
> async function foo() { }
undefined
> foo()
TypeError: Object doesn't support property or method 'MakeMirror'
   at inspectPromise (util.js:204:3)
   at formatValue (util.js:354:5)
   at inspect (util.js:109:3)
   at self.writer (repl.js:342:7)
   at finish (repl.js:463:9)
   at defaultEval (repl.js:273:5)
   at bound (domain.js:281:5)
   at runBound (domain.js:294:5)
   at Anonymous function (repl.js:417:7)
   at emitOne (events.js:96:7)
> foo().then(function() { console.log("done") })
TypeError: Object doesn't support property or method 'MakeMirror'
   at inspectPromise (util.js:204:3)
   at formatValue (util.js:354:5)
   at inspect (util.js:109:3)
   at self.writer (repl.js:342:7)
   at finish (repl.js:463:9)
   at defaultEval (repl.js:273:5)
   at bound (domain.js:281:5)
   at runBound (domain.js:294:5)
   at Anonymous function (repl.js:417:7)
   at emitOne (events.js:96:7)
> done

```

**Comment by jianchun** [comment]
@aruneshchandra What's expected behavior?
@boingoing Do you happen to know about this?
Thanks!

**Comment by targos** [comment]
Async functions return a Promise when called. Do you get the same error with something like `Promise.resolve()` ?

**Comment by aruneshchandra** [comment]
@targos - Yes

**Comment by boingoing** [comment]
I'm not familiar with REPL but looks like util.js is using the mirror debugger to inspect the promise instance. It may be probing for internal promise state. I don't have experience with it. Looks like the API is Debug.MakeMirror. Perhaps this is not supported yet.

@kunalspathak Do you have context on this?

**Comment by kunalspathak** [comment]
Yes, MakeMirror is a v8 specific debugging API that node uses to inspect the properties of an object and Chakracore doesn't have the implementation of it yet.

Sent from Outlook Mobilehttps://aka.ms/blhgte

On Mon, Mar 21, 2016 at 3:18 PM -0700, "Taylor Woll" <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not familiar with REPL but looks like util.js is using the mirror debugger to inspect the promise instance. It may be probing for internal promise state. I don't have experience with it. Looks like the API is Debug.MakeMirror. Perhaps this is not supported yet.

@kunalspathakhttps://github.com/kunalspathak Do you have context on this?

##

**Comment by jianchun** [comment]
Thanks for these info! I prototyped a fake Debug.MakeMirror support to make this look nicer:

```
> async function foo() { }
undefined
> foo()
Promise { undefined }
> foo().then(function() { console.log("done") })
Promise { undefined }
> done

>
```

Currently I can only get "Promise { undefined }" disregarding real status (pending, resolved, ...). If we have APIs to inspect Promise internal states, we could improve this. Do we have any way to inspect? @boingoing

@aruneshchandra Would you like this to get in?

**Comment by boingoing** [comment]
@jianchun The engine tracks internal promise states but they aren't exposed via any Jsrt API. It shouldn't be too hard to add one. The fields you're interested in are JavascriptPromise::status and JavascriptPromise::result, I think.

**Comment by aruneshchandra** [comment]
Having the real fix backed by the new JsRT api will be ideal, however I think we should take the current fix. Also it would be nice to show `Promise { unknown }` which seems more accurate in this case.

**Comment by jianchun** [comment]
@aruneshchandra Changed to

```
> async function foo() {}
undefined
> foo()
Promise { '<unknown>' }
> foo().then(()=>console.log('done'))
Promise { '<unknown>' }
> done

>
```

@agarwal-sandeep @liminzhu How will we inspect a Promise object from a debugger? Specifically need to access its "status" and "result" as @boingoing said.

**Comment by aruneshchandra** [comment]
Sweet - thanx @jianchun !
