### ISSUE TITLE
TTD assert failed: Invalid -- JavascriptAsyncFunction

### ISSUE THREAD

**Issue by davidwesst** [nodejs/node-chakracore#411]
* **Version**: v8.6.0
* **Platform**: Windows 10 Pro 64-bit
* **Subsystem**: npm\lib\utils\lifecycle.js (see attached log for stack trace)

Hello,

I've been trying to get TTD working, and get the attached log with the console output, as seen below. The same error occurs with both [my own project](https://github.com/davidwesst/dw-graphql) and the [TTD demo project](https://github.com/mrkmarron/RFSDemoJS).

If there is any more information I can provide, please let me know.

---

> [master ≡ +0 ~2 -0 !] C:\Users\david\src\RFSDemoJS
> npm start

> rfs-demo@0.1.0 start C:\Users\david\src\RFSDemoJS
> nvs run chakracore/8.6.0 --record index.js
> Recording is enabled (but not yet started)...
> No cloud credentials found -- only local traces will be written.
> process.env.DO_TTD_RECORD is [1]
> process.env.DIAGNOSTICS_BUDDY_STORAGE_CREDENTIALS is [undefined]
> path.resolve('./' is [C:\Users\david\src\RFSDemoJS]
> { engine: '\u001b[32mchakracore\u001b[39m',
>   port: 3000,
>   pid: 7396 }
> Recording started (after main module loaded)...
> TTD assert failed: Invalid -- JavascriptAsyncFunction
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1073807364
> npm ERR! rfs-demo@0.1.0 start: `nvs run chakracore/8.6.0 --record index.js`
> npm ERR! Exit status 1073807364
> npm ERR!
> npm ERR! Failed at the rfs-demo@0.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\david\AppData\Roaming\npm-cache\_logs\2017-10-06T03_46_50_570Z-debug.log 

Log file: 
[2017-10-06T03_46_50_570Z-debug.log](https://github.com/nodejs/node-chakracore/files/1361492/2017-10-06T03_46_50_570Z-debug.log)

**Comment by mike-kaufman** [comment]
@davidwesst - this is a known issue.  Recent integration from node mainline introduced generator functions and async/await in core javascript libraries e.g., in the [module loader](https://github.com/nodejs/node/blob/master/lib/internal/loader/ModuleJob.js#L102)   and [readline](https://github.com/nodejs/node/blob/master/lib/internal/readline.js#L162).  These constructs aren't yet supported in TTD.  We'll be looking to get these supported soon.

If you'd like to play around with TTD, the node-chakracore 8.4 build should work.  

Please let us know if you have any other feedback.

**Comment by jackhorton** [comment]
@davidwesst I have updated the 8.6.0 release notes to clarify the current state of TTD: https://github.com/nodejs/node-chakracore/releases/tag/node-chakracore-v8.6.0

Sorry for the confusion! I am going to close this for now, since the work is being tracked elsewhere.

**Comment by davidwesst** [comment]
Awesome! Thanks for the update. I'll mess around with TTD in 8.4 then, and wait for the update!

Thanks for the quick reply to everything (even though I was slow on getting back to you).
