### ISSUE TITLE
chakrashim: FunctionCallbackInfo::NewTarget returns nullptr

### ISSUE THREAD

**Issue by jackhorton** [nodejs/node-chakracore#413]
https://github.com/nodejs/node-chakracore/commit/4569fd2ebc9d176ce0ab0993769579a5833e0b79 introduced a shim to allow the addons/new-target test to compile, but the test is still marked as flaky and likely will be until we get a good way to access the new.target of a call from JSRT. See https://github.com/Microsoft/ChakraCore/issues/3762 for progress on this.

**Comment by fatcerberus** [comment]
In my experience `new.target` for constructor calls seems to be passed in lieu of `this`--in other words, in `argv[0]`.  So if `isConstructCall` is true then `argv[0]` == new.target, otherwise `new.target` can be assumed to be undefined.

**Comment by jackhorton** [comment]
I am not sure if thats necessarily _supposed_ to be the case, though. My understanding of the issues you had filed over in the main ChakraCore repo was that we didn't necessarily intend for argv[0] === new.target. I can try to dig into this more once some of the Intl work I have wraps up.

**Comment by tinker1968** [comment]
#

**Comment by jackhorton** [comment]
@boingoing this is fixed now, yes?

**Comment by boingoing** [comment]
Yes, should be fixed by Jsrt API `JsCreateEnhancedFunction`.
