### ISSUE TITLE
NAN error - 'JSON': is not a member of 'v8'

### ISSUE THREAD

**Issue by munyirik** [nodejs/node-chakracore#416]
versions:
- chakracore: 8.1.2-pre/x64
- nan: 2.6.2

I was attempting to build https://github.com/fivdi/i2c-bus which uses nan. An error occurs because nan_json.h expects v8:JSON to exist.

**Comment by digitalinfinity** [comment]
@munyirik can you try with a newer version- I think this was fixed in https://github.com/nodejs/node-chakracore/commit/85ccdd165603d9aade32c6e9dc204fcbe331bf15?

**Comment by munyirik** [comment]
Ah, yeah. This is fixed in the latest release. Thanks @digitalinfinity !
