### ISSUE TITLE
Outdated SHASUMS256 for Release v8.6.0

### ISSUE THREAD

**Issue by zackdouglas** [nodejs/node-chakracore#428]
Please update `SHASUMS256.txt` for [the v8.6.0 release](https://github.com/nodejs/node-chakracore/releases/tag/node-chakracore-v8.6.0); the sums for v8.4.0 were carried over.

**Comment by obastemur** [comment]
@MSLaguana ping.

**Comment by MSLaguana** [comment]
I have updated the `SHASUMS256.txt` file as part of the release, thanks for pointing that out!
