### ISSUE TITLE
Please support Linux or OSX

### ISSUE THREAD

**Issue by ysmood** [nodejs/node-chakracore#43]
Is there a Linux or OSX built?

**Comment by xtianus79** [comment]
What do you mean?

**Comment by ysmood** [comment]
Sorry, I thought it didn't support unix. I was wrong. Close the issue.

**Comment by jianchun** [comment]
@ysmood ChakraCore currently only runs on Windows, cross-platform is in the works: https://github.com/Microsoft/ChakraCore/wiki/Roadmap#enhancing-host--platform-support.

**Comment by ysmood** [comment]
Only one question. How to enable async/await support?

```
node --es_staging --harmony
```

Seems doesn't work.

**Comment by jianchun** [comment]
node-chakracore has the support on by default. I'm not sure of the status though. @aruneshchandra Do you know if async/await fully works? I tried a few tests and getting syntax errors around await.

**Comment by aruneshchandra** [comment]
Once #41 gets resolved - using await like this should work.

```
> async function foo() { await Promise.resolve(); return 1; }
async function foo() { await Promise.resolve(); return 1; }
undefined
> foo()
Promise { undefined }
> foo().then(v => console.log(v))
Promise { undefined }
> 1
```
