### ISSUE TITLE
socket.io not working

### ISSUE THREAD

**Issue by laggingreflex** [nodejs/node-chakracore#44]
requiring socket.io doesn't work and fails silently.

It installs correctly

```
npm install socket.io
C:\test\chakrasocket
└─┬ socket.io@1.4.5
```

This is the simple test file:

**index.js**

```
console.log(1);
require('socket.io');
console.log(2);
```

Running it logs 1 but exits silently after it

```
C:\test\chakrasocket>node a
1

C:\test\chakrasocket>
```
- **Version**: v6.0.0-pre5
- **Platform**: Windows 10 64 bit

**Comment by jianchun** [comment]
@laggingreflex I just tried it on my box and it works. Do you launch node-chakracore through "Start -> Node.js (chakracore) command prompt"? (Do you happen to have globally installed npm or node-gyp? Not sure if we have issues there.)
