### ISSUE TITLE
jest-haste-map 22.4.0 breaks in node-chakracore

### ISSUE THREAD

**Issue by jdalton** [nodejs/node-chakracore#477]
Just a heads up. I have a unit test that checks `jest` + `mock-require` and it started failing after with the `jest-haste-map 22.4.0 update (on Windows 10).

\cc @SimenB

**Comment by jdalton** [comment]
It is probably related to this bit https://github.com/facebook/jest/commit/3a2854aeca669b6cd82139de23333fa18fce7c6c#diff-9450b62547fd20fe4b1669dd088f14af.

The error I get is
```
TypeError: Unable to get property 'files' of undefined or null reference
   at Anonymous function (C:\projects\esm\node_modules\jest-haste-map\build\index.js:324:7)
```
It's reading a haste cache file but the file is empty, `""`.

**Comment by jdalton** [comment]
The error I get is
```
TypeError: Unable to get property 'files' of undefined or null reference
   at Anonymous function (C:\projects\esm\node_modules\jest-haste-map\build\index.js:324:7)
```
It's reading a haste cache file but the file is empty, `""`.

**Comment by SimenB** [comment]
Can you try with 22.4.2? Ref facebook/jest#5642.

Doesn't chakra node support `v8.serialize`? Which would be understandable, but then we shouldn't hit that code path anyways.

Underlying change: facebook/jest#5565

**Comment by jdalton** [comment]
I actually worked backwards from 22.4.2. The first version to work again was 22.3.0.

**Comment by MSLaguana** [comment]
The `v8.deserialize` method seems to have nothing to do with v8, and it's implemented in node so we should support it. It looks to me like right now the native methods it calls into are being mis-compiled into do-nothing functions, so it is returning `undefined`.

**Comment by MSLaguana** [comment]
Ah nevermind; the `node_serdes` serialization methods end up depending on a v8 type that we don't mock out, and so the compiler was calling our bluff.

**Comment by mjesun** [comment]
Sorry for the late reply, I just got an email about that (thanks, GitHub...). From what you say it looks like it's not a particular bug in Jest?

What would work as well for you is if you don't provide `v8.serialize` at all. In that case, we default back to an implementation with a standard `JSON.stringify`.

**Comment by MSLaguana** [comment]
The difficulty with that is we kind-of/kind-of-don't support everything in the v8.js file. The simplest thing from our side would be to remove v8.js, but then your `require("v8")` would throw and that looks like it'd be worse for you at the moment. The alternative that you propose is essentially having v8.js as an empty file, which isn't too unreasonable, but as a general rule we try to keep our diff from upstream node as small as possible.

**Comment by digitalinfinity** [comment]
I think it's not unreasonable for v8.js to just return an empty object if process.jsEngine != 'v8'. @addaleax thoughts? (and yes, we probably should get around to supporting serdes at some point, it's still on my backlog 😞)

**Comment by mjesun** [comment]
@MSLaguana I can wrap the V8 require in a `try`/`catch` prior to check `v8.serialize`; would that make things simpler?

**Comment by MSLaguana** [comment]
I've just put out a PR to have the `v8` module be an empty object: https://github.com/nodejs/node-chakracore/pull/491

**Comment by MSLaguana** [comment]
This should be fixed in nightlies now, triggering the fallback to `JSON.parse`

**Comment by kfarnung** [comment]
The fix was also backported to our latest release build:  https://github.com/nodejs/node-chakracore/releases/tag/node-chakracore-v8.10.0
