### ISSUE TITLE
New Contributors for Node-Chakracore

### ISSUE THREAD

**Issue by MSLaguana** [nodejs/node-chakracore#479]
Please add the following contributors to [Node-ChakraCore](https://github.com/orgs/nodejs/teams/node-chakracore) team:

* @sethbrenith - Seth Brenith
* @irinayat-MS - Irina Yatsenko

// cc: @mhdawson, @jasnell

**Comment by joaocgreis** [comment]
cc team maintainers @thefourtheye @aruneshchandra

**Comment by kfarnung** [comment]
I believe @aruneshchandra tried to add them, but they aren't currently a "Member" of the nodejs organization so he wasn't able to.

**Comment by mhdawson** [comment]
Can you confirm that they have both enable 2 factor authentication.  Once you confirm I can send out invites and add them.  I assume they are also both Microsoft employees ?

**Comment by MSLaguana** [comment]
They do indeed have 2FA enabled, and they are both Microsoft employees.

**Comment by mhdawson** [comment]
Invites should be on their way.

**Comment by sethbrenith** [comment]
Thanks!

**Comment by IrinaYatsenko** [comment]
Thank you!
