### ISSUE TITLE
Upstream process.jsEngine

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/node-chakracore#487]
Upstream process.jsEngine so that it allows developers to test for other VMs like ChakraCore to conditionally enable VM specific functionality.

**Comment by kfarnung** [comment]
@digitalinfinity @aruneshchandra 

Does this seem like a reasonable change to propose?

https://github.com/nodejs/node/compare/master...kfarnung:jsengine

**Comment by MSLaguana** [comment]
Most of the change looks good to me, although I'm not sold on the test, from the perspective of having it work with chakracore as well...

**Comment by MSLaguana** [comment]
Maybe have the check make sure that `process.jsEngine in process.versions` instead, get the benefit of making sure that's hooked up as well?

**Comment by MSLaguana** [comment]
And actually, on that note you might want to change the literal "v8" a little further down in `node.cc` to use the `NODE_ENGINE` define instead as well?

**Comment by kfarnung** [comment]
I initially did change that, but it felt weird given that the value is populated by calling `V8::GetV8Version()` so it didn't feel like the right way to go about it.  It's an easy change if we feel strongly about it though.

**Comment by kfarnung** [comment]
I've updated the commit with the feedback, please take another look.

**Comment by MSLaguana** [comment]
Looks good to me.

**Comment by kfarnung** [comment]
I opened the PR:  https://github.com/nodejs/node/pull/19243

**Comment by kfarnung** [comment]
The feedback from upstream is that developers should be using `process.versions['chakracore']` to detect ChakraCore.  This seems to work well for module developers, so I closed the PR.  For tests we still need jsEngine as a straight-forward way to filter tests.
