### ISSUE TITLE
util: util.types.isProxy does not work in Node-ChakraCore

### ISSUE THREAD

**Issue by jackhorton** [nodejs/node-chakracore#488]
Causes `test/parallel/test-util-types` to fail.

**Comment by kfarnung** [comment]
Refs:  https://github.com/Microsoft/ChakraCore/issues/950

**Comment by jackhorton** [comment]
See https://github.com/nodejs/node-chakracore/commit/1e9ba647ac6777cb180314fd400108e940103395#diff-1980aca1cba9a1f0b7278ab1db2c064cR54

**Comment by rhuanjl** [comment]
Is there a reason not to support util.types.isProxy? The JsGetProxyProperties api I added to ChakraCore should enable supporting it. Unsure what the policy for contributing to node-chakracore - but I could try and make a PR to implement this if wanted?

**Comment by kfarnung** [comment]
No reason not to support it, we just hadn't gotten the chance to implement it yet.  The contribution policy is the same as upstream node, feel free to open a PR.

**Comment by rhuanjl** [comment]
@kfarnung Thanks - ok I'll give it a try and I'll see if I can do #523 at the same time.

One question though, is there an existing mechanism for exposing a native function to chakra_shim.js without exposing it globally? (I can't currently find such in the source tree though I may just not be looking closely enough)

**Comment by jackhorton** [comment]
I don't think there is. With that being said, isProxy doesn't have to be in chakra_shim.js, it can be implemented in native (I think most of the other basic types are done in native, and only complex types like MapIterator and SetIterator are in chakra_shim.js). In general, the JS file is a grab bag of "we don't have a native API to do this, but we know how to do it in JS, so do it in JS". Now that we have a native API, the JS version shouldn't be necessary. There will be a relevant change in v8value.cc to remove `IS_TYPE_FUNCTION(IsProxy, isProxy)` and add a real native implementation (`bool Value::IsProxy() const { }`)

**Comment by rhuanjl** [comment]
Ok so I've made working fixes for this and util.inspect's showProxy flag. But trying to run ```make test``` before opening a PR I get multiple errors that are nothing to do with proxies. Are there tests that you expect to fail at the moment?

e.g.s
1. test/parallel/test-console-no-swallow-stack-overflow.js -> crashed
2. test/parallel/test-console-sync-write-error.js -> timeout
3. test/parallel/test-util-types.js -> has an ESModule test which fails as CC doesn't support ESModules
4. test/parallel/test-http2-respond-file-fd-invalid.js -> fails by calling mustNotCall()
5. test/message/stack_overflow.js -> crashed

I can put an if (!common.isChakraEngine) around the ESModule test in test-util-types.js but unsure on the other ones.

**Comment by kfarnung** [comment]
`make test` already ignores some tests (take a look at the *.status files) and should come back clean, go ahead and open a PR and we can figure out what’s going on with the tests.

-Kyle

**Comment by kfarnung** [comment]
`make test` already ignores some tests (take a look at the *.status files) and should come back clean, go ahead and open a PR and we can figure out what’s going on with the tests.

**Comment by jackhorton** [comment]
I am also surprised to hear that `make test` isn't working for you, since we do official node CI runs as well as internal CI runs on Linux multiple times a day. I haven't personally ran node-chakracore tests on Linux recently, but does this have something to do with how on windows, we usually specify `vcbuild.bat test-ci ignore-flaky` rather than just `vcbuild.bat test`?

**Comment by MSLaguana** [comment]
On Linux, we use `FLAKY_TESTS=dontcare make test-ci` and don't expect any unmarked failures (unless there are machine configuration issues). I just double checked our latest CI and the only failures there are artifacts of the vm that we run it in, and none of them are ones you mention above.
