### ISSUE TITLE
shot tests failing on Node-ChakraCore

### ISSUE THREAD

**Issue by digitalinfinity** [nodejs/node-chakracore#499]
* **Version**: 10.0.0-nightly
* **Platform**: all
* **Subsystem**: chakracore

Repro steps (attempted on Linux):
- Get latest node-ChakraCore
- git clone https://github.com/hapijs/shot 
- cd shot
- npm install
- npm test

Result: 43 pass, 1 fail

```
44 tests complete
Test duration: 157 ms
Assertions count: 72 (verbosity: 1.64)
The following leaks were detected:CollectGarbage
Coverage: 100.00%
Linting results: No issues
```

**Comment by digitalinfinity** [comment]
Chatting with @MSLaguana the root cause here is that CollectGarbage is getting exposed in Node-ChakraCore without --expose-gc. We should change it so that ChakraCore does not expose this function unless explicitly requested

**Comment by geek** [comment]
@digitalinfinity if you want to use the same checks, here is how we have it in lab: https://github.com/hapijs/lab/blob/master/lib/leaks.js

**Comment by IrinaYatsenko** [comment]
GlobalObject.cpp has the following comment: "We expose the CollectGarbage API with flag for compat reasons." -- and then we expose CollectGarbage as "undefined". Being able to configure GC was added in Windows TH2 (Change 1591331). I think the back compat here means IE.
