### ISSUE TITLE
Compiling modules requiring native binding

### ISSUE THREAD

**Issue by delfinof** [nodejs/node-chakracore#5]
I am trying the chackra node.js engine and was checking if it supports native bindings (indeed this is not clear from the documentation...).

When I try to install the headers with node-gyp I get the following output:

D:\nodejs_chakra>node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@5.0.0-0 | win32 | ia32
gyp http GET https://nodejs.org/dist/v5.0.0-0/node-v5.0.0-0-headers.tar.gz
gyp http 404 https://nodejs.org/dist/v5.0.0-0/node-v5.0.0-0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v5.0.0-0/node-v5.0.0-0-headers.tar.gz
gyp ERR! stack    at Anonymous function (C:\Users\Francesco\AppData\Roaming\npm\node_modules\node-gyp\lib\install.js:244:11)
gyp ERR! stack    at emitOne (events.js:82:7)
gyp ERR! stack    at emit (events.js:169:7)
gyp ERR! stack    at Request.prototype.onRequestResponse (C:\Users\Francesco\AppData\Roaming\npm\node_modules\node-gyp\node_modules\request\request.js:951:5)
gyp ERR! stack    at emitOne (events.js:77:5)
gyp ERR! stack    at emit (events.js:169:7)
gyp ERR! stack    at parserOnIncomingClient (_http_client.js:421:3)
gyp ERR! stack    at parserOnHeadersComplete (_http_common.js:88:5)
gyp ERR! stack    at socketOnData (_http_client.js:311:3)
gyp ERR! stack    at emitOne (events.js:77:5)
gyp ERR! stack    at emit (events.js:169:7)
gyp ERR! stack    at readableAddChunk (_stream_readable.js:146:9)
gyp ERR! stack    at Readable.prototype.push (_stream_readable.js:110:3)
gyp ERR! stack    at onread (net.js:523:5)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files (x86)\NodejsUwp\Console\node.exe" "C:\Users\Francesco\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "install"
gyp ERR! cwd D:\nodejs_chakra
gyp ERR! node -v v5.0.0-0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

Is there a misconfiguration on my development machine or native modules are not supposed to work?

Thanks

**Comment by jianchun** [comment]
@delfinof  The official node-gyp does not work because it does not know about Node.js with Chakra. I assume you have installed Node.js Tools for Windows IoT. It includes Node.js with Chakra and comes with a customized version of node-gyp. Please run that copy of node-gyp. Launch "Node.js (chakra) command prompt". The customized node-gyp is at "c:\Program Files (x86)\NodejsUwp\Console\node_modules\npm\bin\node-gyp-bin\node-gyp.cmd".

**Comment by jianchun** [comment]
Also please note that globally installed node-gyp by the user has higher priority... To run the customized node-gyp, please either try add `c:\Program Files (x86)\NodejsUwp\Console\node_modules\npm\bin\node-gyp-bin` to front of PATH, or uninstall global node-gyp (`npm uninstall -g node-gyp`).

**Comment by jianchun** [comment]
Recently released MSIs all have this issue resolved.
