### ISSUE TITLE
Building with enable-vtune fails due to deprecated <hash_map>

### ISSUE THREAD

**Issue by choikwa** [nodejs/node-chakracore#50]
Building with below command fails due to deprecated <hash_map>. It should be replaced with  <unordered_map>
cmdline: vcbuild chakracore x86 nosign enable-vtune

Affected file: ./deps/v8/src/third-party/vtune/vtune-jit.cc

Also, not sure if enable-vtune is enabled with chakracore option since above path points to v8
- **Version**: 6.0.0-pre
- **Platform**: Win8.1 64bit
- **Subsystem**: _optional. if known - please specify affected core module name_

**Comment by jianchun** [comment]
@choikwa What command line exactly triggers this failure? As you said, that was in `v8/src` and should not affect building with chakracore (not supported really).

**Comment by jianchun** [comment]
@orangemocha This issue exists in node.js (v8). Should we open a new issue on nodejs/node?

In node-chakracore, we can either do nothing (likely it does not work), or modify vcbuild.bat to emit an error message. Probably doing nothing is fine... what do you prefer?

**Comment by orangemocha** [comment]
I confirm that I can reproduce the same on nodejs/master. I opened https://github.com/nodejs/node/issues/6422, and we can close this one.

In terms of what to do for vcbuild, I would prefer an error message that says that `enable-vtune` is not compatible with `chakracore`. But until it's proven to not work we can be optimistic :wink:
