### ISSUE TITLE
Fail to $nvs add chakracore/latest

### ISSUE THREAD

**Issue by hoonhan** [nodejs/node-chakracore#506]
* **Version**: v9.10.0
* **Platform**: Linux home 3.13.0-32-generic #57~precise1-Ubuntu SMP Tue Jul 15 03:50:54 UTC 2014 i686 i686 i386 GNU/Linux

I'm now trying to add chakracore/latest as mentioned in the instruction, but it returns a message that
"Platform package not available for version: chakracore/8.10.0/x86"

I know that this package is available now, but my machine cannot do that.

**Comment by MSLaguana** [comment]
node-chakracore only supports x64 for Linux; are you running a 64bit OS?

**Comment by hoonhan** [comment]
Oh, that was the very reason. Thanks
