### ISSUE TITLE
Expose (and tie) ChakraCore options like --v8-options

### ISSUE THREAD

**Issue by choikwa** [nodejs/node-chakracore#51]
Showing which options that could be passed to ChakraCore would be nice for debugging and customizing purposes.

> $ ~/node-chakracore/Release/node.exe --v8-options
> Options:
> --use_strict (enforce strict mode)
>     type: bool  default: false
> --expose_gc (expose gc extension)
>     type: bool  default: false
> --harmony (Ignored in node running with chakracore)
> --debug (Ignored in node running with chakracore)
> --stack-size (Ignored in node running with chakracore)
- **Version**: v6.0.0-pre
- **Platform**: Win8.1 64bit
- **Subsystem**: _optional. if known - please specify affected core module name_

**Comment by jianchun** [comment]
@choikwa ChakraCore does not accept customizing options (at least yet). The output you posted are exactly what's available now and are implemented by the "shim" code in this repo.
