### ISSUE TITLE
util.inspect showProxy option doesn't work in node-chakra

### ISSUE THREAD

**Issue by jdalton** [nodejs/node-chakracore#523]
The `util.inspect` option `showProxy` doesn't work in node-chakra

```js
util.inspect(new Proxy({},{}), { showProxy: true })
// "{}" but should be "Proxy [ {}, {} ]"
```
The [`showProxy` option](https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_util_inspect_object_options) was added in Node 6.x.

**Comment by jdalton** [comment]
The `showProxy` option was added in Node 6.x.

**Comment by jdalton** [comment]
@kfarnung 

This issue might not be affected by https://github.com/nodejs/node-chakracore/commit/5d023bb320de120bab92f42f2bf3614b569e42bc since `util.inspect` relies on `process.binding('util').getProxyDetails(proxy)` which will unwrap a proxy and return an array of `[theOriginalValue, theActualHandlerObjectProvidedToTheProxyConstructor]`

**Comment by kfarnung** [comment]
I just tried out the original repro with that change and it looks fixed to me:

```console
> util.inspect(new Proxy({},{}), {showProxy: true})
'Proxy [ {}, {} ]'
```

@rhuanjl implemented the `v8::Proxy::GetTarget()` and `v8::Proxy::GetHandler()` methods in the shim which are used by `GetProxyDetails` in `node_util.cc`. Some existing (but previously disabled) tests were reenabled in that commit which do exercise `util.inspect`.

**Comment by rhuanjl** [comment]
@jdalton I tested the specific case from this issue before committing as well as re-enabling the test file test-util-inspect-proxy.js which covers this api.

For extra detail if wanted:
```process.binding('util').getProxyDetails``` is implemented within node as:
```cc
env->SetMethod(target, "getProxyDetails", GetProxyDetails);

static void GetProxyDetails(const FunctionCallbackInfo<Value>& args) {
  // Return undefined if it's not a proxy.
  if (!args[0]->IsProxy())
    return;

  Local<Proxy> proxy = args[0].As<Proxy>();

  Local<Array> ret = Array::New(args.GetIsolate(), 2);
  ret->Set(0, proxy->GetTarget());
  ret->Set(1, proxy->GetHandler());

  args.GetReturnValue().Set(ret);
}
```

The three methods I implemented for chakrashim in https://github.com/nodejs/node-chakracore/commit/5d023bb320de120bab92f42f2bf3614b569e42bc were:
value->IsProxy() 
proxy->GetTarget() and
proxy->GetHandler()

i.e. the 3 calls that GetProxyDetails requires.

**Comment by jdalton** [comment]
:tada:!
