### ISSUE TITLE
Move `master` to ChakraCore 1.10

### ISSUE THREAD

**Issue by kfarnung** [nodejs/node-chakracore#540]
There are a bunch of improvements in the 1.10 release including ICU support for Intl.

**Comment by alexlamsl** [comment]
Just curious — hasn't this been done with the release of `node-chakracore@10.6.0`?

**Comment by sethbrenith** [comment]
Yep, good catch

**Comment by kfarnung** [comment]
Whoops, forgot to close this when it landed.
