### ISSUE TITLE
npm adduser not working

### ISSUE THREAD

**Issue by alexlamsl** [nodejs/node-chakracore#55]
### v8

```
>ver
Microsoft Windows [Version 6.3.9600]

>node -v
v5.10.1

>npm -v
3.8.3

>npm adduser
Username: <user>
<user>
Password:
Password:<pass typed, not shown>
Email: (this IS public) <email>
Logged in as <user> on https://registry.npmjs.org/.
```

Notice the problems with duplicated outout, but at least I can login...
### chakracore

```
>ver
Microsoft Windows [Version 6.3.9600]

>node -v
v6.0.0-pre6

>npm -v
3.7.3

>npm adduser
Username: <user>
Password: <pass typed & shown!>

Email: (this IS public)
npm ERR! cb() never called!
```

I wasn't even offered a chance to type my email after plain-text password entry; it just errs out.

**Comment by alexlamsl** [comment]
I have a quick browse through https://github.com/npm/npm/releases between 3.7.3 and 3.8.3, but couldn't find any mentions of `adduser` except for docs

**Comment by jianchun** [comment]
@alexlamsl Thanks for reporting this issue. I can reproduce it with node-chakracore-v6.0.0-pre6, and seems the issue goes away with https://github.com/nodejs/node-chakracore/pull/52 (which does include NPM 3.8.3). Will keep an eye on this and propose a new release next week to fix it.

**Comment by alexlamsl** [comment]
@jianchun I'll be sure to check `6.0.0-pre7` out - thanks!

**Comment by jianchun** [comment]
@alexlamsl Please try out `6.0.0-pre7`, just [published](https://github.com/nodejs/node-chakracore/releases)

**Comment by alexlamsl** [comment]
@jianchun works like a charm (even without the double prompts that `5.10.1` have) - thanks!

**Comment by MylesBorins** [comment]
@alexlamsl can you expand on the double prompt?

**Comment by alexlamsl** [comment]
@TheAlphaNerd See the v8 section in the first comment:
https://github.com/nodejs/node-chakracore/issues/55#issue-147203996

**Comment by jianchun** [comment]
I have also seen the double prompts _intermittently_.
