### ISSUE TITLE
child_process.* exits with -2147483645

### ISSUE THREAD

**Issue by alexandruradovici** [nodejs/node-chakracore#56]
- **Version**: v6.0.0-pre2
- **Platform**: Windows IoT Core, Raspberry Pi 2 Model B
- **Subsystem**: child_process

Any function related to spawn from child_process makes the program crash with %errorlevel% -2147483645.

I am using it with ssh. Pressing any keys like arrow keys blocks the console and prevents any other ssh connection.

Here is the code the I use

```
const spawn = require('child_process').spawn; 
const bat = spawn('cmd.exe', []);
```

**Comment by aruneshchandra** [comment]
@alexandruradovici - I am going to close this issue, since we were able to resolve it over the phone.  Feel free to re-open if it still exists.

**Comment by alexandruradovici** [comment]
The solution was to upgrade the Windows IoT Core to https://developer.microsoft.com/en-us/windows/iot/win10/getstarted/setupyourdevicemanually
