### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by leonbett** [nodejs/node-chakracore#573]
Hi,

I'm trying to build node-chakracore like so: "make -j4 -C out BUILDTYPE=Debug".
The build fails however:
../src/node_api_jsrt.cc: In function ‘napi_status napi_get_value_int64(napi_env, napi_value, int64_t*)’:
../src/node_api_jsrt.cc:1544:7: error: ‘isfinite’ is not a member of ‘std’
   if (std::isfinite(valueDouble)) {
       ^~~

This is the toolchain I'm using:

clang version 5.0.0-3~16.04.1 
clang++ version 5.0.0-3~16.04.1
gcc (Ubuntu 6.4.0-17ubuntu1~16.04) 6.4.0 20180424
g++ (Ubuntu 6.4.0-17ubuntu1~16.04) 6.4.0 20180424
GNU Make 4.1
Python 2.7.12

I'd be glad if somebody could point out what I'm doing wrong.

**Comment by kfarnung** [comment]
Are you trying to get a debug build?

Did you try:
```console
$ ./configure --engine=chakracore --debug
$ make -j4
```

Can you try that and report back?  `std::isfinite` has been in the standard since C++11, so I don't know why it wouldn't exist in your environment.

**Comment by leonbett** [comment]
Hi kfarnung,

I do want to get a debug build.
Building on another machine using your commands worked perfectly.

Thanks.
