### ISSUE TITLE
Does the Persistent<T>::SetWeak() do the same thing in v8 compared to chakra?

### ISSUE THREAD

**Issue by yuej-jin** [nodejs/node-chakracore#60]
- **Version**:
- **Platform**:
- **Subsystem**:

Or is there a "weak reference" conception in chakra? Because I notice chakra only has "JsRef" conception.

So I wonder if there is difference between the "Weak reference" management in v8 and chakrashim.
As I read in v8.h: There is no guarantee as to _when_ or even _if_ the callback is invoked. But in chakra, what will happen?

``` C++
/**
 *  Install a finalization callback on this object.
 *  NOTE: There is no guarantee as to *when* or even *if* the callback is
 *  invoked. The invocation is performed solely on a best effort basis.
 *  As always, GC-based finalization should *not* be relied upon for any
 *  critical form of resource management!
 */
template <typename P>
V8_INLINE V8_DEPRECATED(
    "use WeakCallbackInfo version",
    void SetWeak(P* parameter,
                 typename WeakCallbackData<T, P>::Callback callback));
```

**Comment by jianchun** [comment]
My answer is basically "yes". ChakraShim's `Persistent<T>::SetWeak` does the same thing, and also `no guarantee as to when or even if the callback is invoked`. With Chakra a `strong` reference is managed through JsAddRef and JsRelease. Without holding a strong reference, you can use [`JsSetObjectBeforeCollectCallback`](https://msdn.microsoft.com/en-us/library/mt125488%28v=vs.94%29.aspx) to set a similar `weak callback` onto a JavaScript object. That's how ChakraShim implements the V8 API.
