### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by alexandruradovici** [nodejs/node-chakracore#61]
- **Version**: 5.10
- **Platform**: Windows 10 IoT Core
- **Subsystem**: console

console.log should put \r\n as line ending, now it is only \n.

**Comment by jianchun** [comment]
Do you have a repro on Windows desktop? Is it from node.exe? (I'm asking because the UWP support in node.dll customized console).

**Comment by alexandruradovici** [comment]
I am running node.exe version 5.10 on Windows 10 IoT Core. It is not built into an UWP software.

**Comment by jianchun** [comment]
@alexandruradovici I tried official node.js (v8) 5.10.1 and it reproduces. Looks this is not a node-chakra issue.

**Comment by MylesBorins** [comment]
@jianchun can you try and the latest versions of v0.10 -> v4 to see if they are all affected?

**Comment by kfarnung** [comment]
I'll verify that this is no longer the case.

**Comment by kfarnung** [comment]
I tried the nightly build of [node-chakracore from 5/30](https://nodejs.org/download/chakracore-nightly/v8.0.0-nightly20170530e35fd86558/) on a Raspberry Pi 3 running Windows IOT and I'm seeing correct behavior around `console.log`.  If you're still seeing this issue, please let us know.
