### ISSUE TITLE
Problems installing `npm i sleep` with node-chakracore 10.13.0.

### ISSUE THREAD

**Issue by jdalton** [nodejs/node-chakracore#610]
When installing `npm i sleep` with node-chakracore 10.13.0 I'm getting the following error:
```
LINK : fatal error LNK1181: cannot open input file 'chakracore.lib' [C:\projects\esm\node_modules\sleep\build\node_slee
p.vcxproj]
```
If I switch to node-chakracore 10.6.0 `npm i sleep` will complete successfully.

**Comment by digitalinfinity** [comment]
@boingoing can you take a look please?

**Comment by boingoing** [comment]
I don't see this locally when I do `npm i sleep` with node-chakracore 10.13.0. The install completes successfully. To test this, I used nvs (`nvs add chakracore/10`) but it should be equivalent to other methods. Can you share the npm log?

**Comment by jdalton** [comment]
Thanks @boingoing!

I'm beginning to think my system may be in a bad state. I'll close this for now. Glad it couldn't repro.
