### ISSUE TITLE
--v8-options not working

### ISSUE THREAD

**Issue by chopdown** [nodejs/node-chakracore#612]
* **Version**: node-chakracore-v10.13.0
* **Platform**: Windows 10
* **Subsystem**: Windows 10

It works on node-chakracore-v10.6.0. Commit: https://github.com/nodejs/node-chakracore/commit/29a71bae40ffa0bbc8ba6b2bdf051a09987da7f7 remove this implementation.  It's need by [v8flags](https://www.npmjs.com/package/v8flags), depend by [gulp module](https://www.npmjs.com/package/gulp). Hope this will be implemented.

**Comment by kfarnung** [comment]
Good catch, this was missed when taking in the latest changes from upstream.  It should be relatively simple to implement the missing function:

https://github.com/nodejs/node-chakracore/blob/38520056313bc747e3ca6dcc7598c2e51394c0ac/deps/chakrashim/src/v8v8.cc#L108-L110

**Comment by chopdown** [comment]
I implemented a version, make things work, but not sure the original intention.

**Comment by kfarnung** [comment]
The fix looks good to me, thanks for the quick PR!
