### ISSUE TITLE
IONIC FRAMEWORK

### ISSUE THREAD

**Issue by shravyabu** [nodejs/node-chakracore#67]
- **Version**:
- **Platform**:
- **Subsystem**:

Hi Everyone,

I have installed ionic, but when i try to create a project, I am facing below error, re-evaluating native module sources is not supported if you are using the graceful-fs module , please update..

Could you please help .

Thanks in Advance,
shravs

**Comment by jianchun** [comment]
Looks like this is the same as #34?

**Comment by shravyabu** [comment]
Thanks Guys!
