### ISSUE TITLE
ActiveX

### ISSUE THREAD

**Issue by kasajian** [nodejs/node-chakracore#7]
Since Internet Explorer use Chakra, and in Internet Explorer one can new-up an ActiveXObject instance to access safe-COM objects, does that mean that this open source version of Chakra can do the same?   If so, does that mean I can execute that type of code from within version of node that's bound to Chakra?

I want to be able to execute code that looks like this:
    var xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");

**Comment by amphineko** [comment]
@kasajian Why you want to do that, it seems that this kind of code will be only available on node.js with Chakra, not portable. :(

As what I see, ActiveX calling is not a part of ChakraCore (see https://github.com/Microsoft/ChakraCore/wiki/Architecture-Overview), so accessing to COM objects should be enabled on your own by writing APIs for it. But I'm not sure if I'm wrong.

In further, you can also access COM objects in vanilla node.js through that way.

**Comment by jianchun** [comment]
@amphineko is correct. Node.js with ChakraCore doesn't come with ActiveXObject support. I agree you could write a native addon module if you really need it.

**Comment by nicole-ashley** [comment]
@kasajian: The Chakra that was open-sourced was the new one from Microsoft Edge only, not the one available in Internet Explorer.

**Comment by Yongqu** [comment]
Also chakra is used by edge browser not internet explorer. edge does not support activeX objects.

**Comment by nicole-ashley** [comment]
@Yongqu: Chakra JScript engine was used in IE, but not this Chakra JavaScript engine. That is probably where the confusion lies.

**Comment by kasajian** [comment]
@amphineko with regard to your question as to why I need to do that.   I would rather not pollute this thread with regard to why I need to do something.   For the purpose of discussing whether or not something is supported does not require explanation for why I need the functionality.   I prefer keep the discussion succict.   My question was promptly answered by the Chakra team as well, and I appreciate the follow up.

If you want more details as to why this is something that's necessary for us, feel free to contact me directly and we can talk about it offline: kasajian@gmail.com

Thank you again for the prompt response.

**Comment by kunalspathak** [comment]
@kasajian - Is there anything that need to be answered or its fine to close the issue?
