### ISSUE TITLE
CPU Profiling

### ISSUE THREAD

**Issue by yunong** [nodejs/node-chakracore#8]
Is there support for profiling of JS stack frames in Chakra? With the V8 engine, you could profile the stack frames at runtime. This is critical as it allows us to objectively observe, compare, and profile the CPU usage of our process. This is possible in both Linux (http://yunong.io/2015/11/23/generating-node-js-flame-graphs/) and Illumos (https://nodejs.org/en/blog/uncategorized/profiling-node-js/)

**Comment by brendangregg** [comment]
Perhaps one can do this using the profile provider from Windows DTrace? https://github.com/prash-wghats/DTrace-win32

For Linux perf_events, if frame pointers work, then it's just a matter of dumping a /tmp/perf-PID.map file for the symbol lookups (http://www.brendangregg.com/blog/2014-09-17/node-flame-graphs-on-linux.html).

**Comment by MikeHolman** [comment]
Chakra registers js stack frames with ETW, so you can use any tool which reads this. I would recommend using tools WPR and WPA (included in the Windows SDK). It has a bit of a learning curve, but is very powerful!

**Comment by kunalspathak** [comment]
> Chakra registers js stack frames with ETW,

Chakra do register js stack frames, but Chakracore doesn't. So if you want to get profiling information, you might need [node+chakra](https://github.com/ms-iot/ntvsiot/releases/tag/node-chakra-5.5.0) that runs with `chakra.dll` on your windows 8.1+ machines.
Using that and tools like WPA/WPR that @MikeHolman  pointed out, you can record the ETW events and see it, something like this:

![image](https://cloud.githubusercontent.com/assets/12488060/13127143/c27b0168-d582-11e5-8b73-b1f5503b406c.png)

**Comment by MikeHolman** [comment]
@kunalspathak Ah didn't realize this isn't supported in ChakraCore. I've opened https://github.com/Microsoft/ChakraCore/issues/328 to discuss possibility of adding this.

**Comment by digitalinfinity** [comment]
@kunalspathak we should revisit this issue now that ChakraCore has ETW support.

**Comment by kunalspathak** [comment]
I will play around with this when i get chance and update this issue with the instructions on how to use it. Note that this will not be usable until we bring ETW change into nodejs/chakracore-master.

**Comment by kfarnung** [comment]
Windows has support for this and @MSLaguana is looking into adding support for Linux.

**Comment by MSLaguana** [comment]
Node-chakracore now has support for JITted frames in ETW on windows, and using the linux `perf` tool on linux/mac. For the non-windows cases currently you need to compile the support in by defining `=PERFMAP_TRACE_ENABLED=1`, which will register a signal handler for `SIGUSR2` (or another signal if you provide another define). When that signal handler is triggered, it will write out a file `/tmp/perf-<pid>.map` which can be parsed by the perf tool to give names to JIT compiled frames.

**Comment by yunong** [comment]
@MSLaguana This is great! Thanks so much for adding this, Chakra is definitely a step ahead of the competition when it comes to CPU profiling. Is it possible to provide a default signal and make this part of the default distribution of Chakra? This would then enable CPU profiling right out of the box for everyone.

**Comment by MSLaguana** [comment]
I had considered that, but the number of available signals is fairly low, and node is already using sigusr1 so if I also caused node-chakracore to use sigusr2 as well then apps would have no signals left that they could override themselves. I discussed it with @digitalinfinity but I'm not sure we'd come to a solid conclusion either way.

**Comment by digitalinfinity** [comment]
@Yunong however we're still relatively new to the Linux world, so if you have thoughts on what the default behavior should be, we'd love to know! Right now, our thinking is that opt-in is the way to go, and maybe we can make it opt-in at runtime (perhaps with some form of signal-chaining?), but if you have some insight on how we should make it on by default without inconveniencing embedders, we're all ears!

**Comment by yunong** [comment]
@digitalinfinity What about providing a runtime argument to Chakra that can opt into this without having to recompile? Let me also chat with some folks at Netflix and get back to you with some possible other solutions.
