### ISSUE TITLE
invalid option --nolazy

### ISSUE THREAD

**Issue by XelaMon** [nodejs/node-chakracore#84]
- **Version**: v7.0.0-pre8
- **Platform**: Windows 10 x64
- **Subsystem**: Unknown

I am working on a new application in TypeScript. I have installed the node.js and TypeScript tools on Visual Studio 2015 and created a new 'Starter Node.js Express 3 Application'. I cannot run the template that is generated because I get the error 'invalid option --nolazy'. Apparently the --nolazy option is used to hit breakpoints reliably. Is there any way to enable this option in node with ChakraCore?

**Comment by kfarnung** [comment]
I'm not seeing an error when passing `--nolazy` to [8.0.0-pre3](https://github.com/nodejs/node-chakracore/releases/tag/node-chakracore-8.0.0-pre3).
