### ISSUE TITLE
Unable to query Azure DB from Windows 10 IoT Core

### ISSUE THREAD

**Issue by matejv1** [nodejs/node-chakracore#86]
- **Version**: v5.10.1-0
- **Platform**: Windows 10 IoT Core
- **Subsystem**: node-mssql , tedious

I'm unable to query Azure MS SQL DB from Windows 10 IoT Core (Raspberry Pi). Will this ever be supported or it already should be?  

I've created sample so we can reproduce issue:
https://github.com/matejv1/nodejs.universal-windows-app.connect-to-azure

It works on Windows 10 - if I just run "node server.js". When debugging or deploying to Raspberry Pi, the app just crashes.

Hopefully someone will give some feedback.

I've posted an issue to node-mssql repository as well. Might be tedious the issue. 

Thanks.

**Comment by kfarnung** [comment]
@munyirik Can you take a look at this?

**Comment by munyirik** [comment]
I've moved this issue to https://github.com/ms-iot/ntvsiot/issues/128 (since this is a node UWP issue). Please close this.

**Comment by kfarnung** [comment]
Thanks @munyirik!
